from __future__ import annotations

import hashlib
import mimetypes
import re
from collections.abc import AsyncIterator
from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from ai_do_api.domains.ai.gateway import (
    AiGatewayContextPack,
    LlmWorkloadContext,
    stream_llm,
)
from ai_do_api.domains.auth.models import User, utcnow_naive
from ai_do_api.domains.auth.security import new_id
from ai_do_api.domains.document_processing.extractors import UnsupportedDocumentType
from ai_do_api.domains.qna.extraction import extract_attachment_text
from ai_do_api.domains.qna.constants import (
    QNA_DEFAULT_CATEGORY,
    QNA_SCOPE_KIND,
    QNA_DOC_SOURCE_KIND,
    QNA_DOCUMENT_RESOURCE_TYPE,
    QNA_KIND_NOTICE,
    QNA_KIND_UPLOAD,
    QNA_MAX_BODY_CHARS,
    QNA_NOTICE_CATEGORY,
)
from ai_do_api.domains.qna.dispatch import dispatch_board_sync
from ai_do_api.domains.qna.models import QnaDocument
from ai_do_api.domains.qna.object_storage import (
    build_company_notice_attachment_storage_key,
    build_company_upload_storage_key,
    build_notice_attachment_storage_key,
    build_upload_storage_key,
    put_qna_object,
    read_qna_object,
)
from ai_do_api.domains.rag import application as rag_application
from ai_do_api.domains.rag.contracts import (
    RagAnswerMode,
    RagGroundedAnswer,
    RagGroundedCitation,
    RagQueryHit,
    RagQueryResponse,
    RagScopeKind,
    RagSyncOperation,
)
from ai_do_api.domains.rag.default_source_adapters import ensure_rag_source_adapters_registered
from ai_do_api.domains.rag.grounded_answer_assembly import (
    DEFAULT_GROUNDED_ANSWER_ASSEMBLER,
)
from ai_do_api.domains.rag.outbox import enqueue_rag_sync_job
from ai_do_api.domains.retrieval import application as retrieval_application
from ai_do_api.domains.retrieval.partitioning import assign_default_partition
from ai_do_api.domains.retrieval.projection_fencing import record_projection_event

_ATTACHMENT_CONTROL_CHARS_RE = re.compile(r"[\r\n\t]+")
_URL_RE = re.compile(r"https?://[A-Za-z0-9._~:/?#\[\]@!$&'()*+,;=%-]+", re.IGNORECASE)
_URL_LOOKUP_QUERY_RE = re.compile(
    r"(주소|url|URL|링크|사이트|홈페이지|접속|몰|portal|site)",
    re.IGNORECASE,
)
_QUERY_TOKEN_RE = re.compile(r"[A-Za-z0-9가-힣]+")
_QUERY_STOP_WORDS = {
    "url",
    "주소",
    "링크",
    "사이트",
    "홈페이지",
    "접속",
    "알려줘",
    "뭐야",
    "무엇",
    "어디",
    "어디야",
    "입니다",
    "인가",
    "은",
    "는",
    "이",
    "가",
    "을",
    "를",
    "의",
    "에",
    "와",
    "과",
    "및",
}


@dataclass(frozen=True, slots=True)
class _UrlMention:
    label: str
    url: str
    hit: RagQueryHit
    quote: str


class QnaAnswerGenerationError(RuntimeError):
    """Raised when the Q&A answer must be generated by the LLM but it degraded."""


@dataclass(frozen=True, slots=True)
class QnaAnswerDelta:
    text: str


@dataclass(frozen=True, slots=True)
class QnaAnswerCompleted:
    response: RagQueryResponse


QnaAnswerStreamEvent = QnaAnswerDelta | QnaAnswerCompleted


def _checksum(*parts: object) -> str:
    digest = hashlib.sha256()
    for part in parts:
        digest.update(str(part or "").encode("utf-8"))
        digest.update(b"\x00")
    return digest.hexdigest()


def _truncate(text: str) -> str:
    text = text or ""
    if len(text) > QNA_MAX_BODY_CHARS:
        return text[:QNA_MAX_BODY_CHARS] + "\n[이하 생략]"
    return text


def normalize_attachment_name(filename: str) -> str:
    """Return a display/storage filename, not a groupware path fragment."""
    normalized = (filename or "").replace("\\", "/").strip()
    normalized = normalized.split("?", 1)[0].split("#", 1)[0].strip().strip("/")
    normalized = normalized.rsplit("/", 1)[-1].strip()
    normalized = _ATTACHMENT_CONTROL_CHARS_RE.sub(" ", normalized).strip()
    return normalized or "attachment"


def normalize_attachment_names(filenames: list[str] | None) -> list[str]:
    seen: set[str] = set()
    normalized: list[str] = []
    for raw_name in filenames or []:
        name = normalize_attachment_name(str(raw_name))
        if name in seen:
            continue
        seen.add(name)
        normalized.append(name)
    return normalized


def _meaningful_query_terms(query: str) -> list[str]:
    terms: list[str] = []
    seen: set[str] = set()
    for match in _QUERY_TOKEN_RE.finditer(query.lower()):
        token = match.group(0).strip()
        if len(token) < 2 or token in _QUERY_STOP_WORDS or token in seen:
            continue
        seen.add(token)
        terms.append(token)
    return terms


def _is_url_lookup_query(query: str) -> bool:
    return bool(_URL_LOOKUP_QUERY_RE.search(query or ""))


def _hit_lookup_text(hit: RagQueryHit) -> str:
    return "\n".join(
        part for part in [hit.title or "", hit.summary or "", hit.excerpt or ""] if part
    )


def _cleanup_url(raw_url: str) -> str:
    return raw_url.rstrip(".,;:)]}>\"'")


def _cleanup_url_label(raw_label: str, *, fallback: str) -> str:
    label = re.sub(r"^[\s\-–—•※·\d.)]+", "", raw_label or "").strip()
    label = re.sub(r"\bURL\b", "", label, flags=re.IGNORECASE)
    label = re.sub(r"\s+", " ", label).strip(" :-：")
    return label or fallback


def _label_for_url(*, before: str, hit: RagQueryHit, terms: list[str]) -> str:
    tail = before[-100:]
    label_match = re.search(
        r"([A-Za-z0-9가-힣+#&·\s()_-]{2,40})\s*(?:URL|주소)?\s*[:：]\s*$",
        tail,
        flags=re.IGNORECASE,
    )
    fallback = terms[0] if terms else hit.title or "관련 링크"
    if label_match:
        return _cleanup_url_label(label_match.group(1), fallback=fallback)
    for term in terms:
        if term in tail.lower():
            return _cleanup_url_label(term, fallback=fallback)
    return _cleanup_url_label(hit.title or fallback, fallback=fallback)


def _url_mentions_for_hit(hit: RagQueryHit, *, terms: list[str]) -> list[_UrlMention]:
    text = _hit_lookup_text(hit)
    if not text:
        return []
    mentions: list[_UrlMention] = []
    for match in _URL_RE.finditer(text):
        url = _cleanup_url(match.group(0))
        start, end = match.span()
        before = text[max(0, start - 140) : start]
        after = text[end : min(len(text), end + 80)]
        context = f"{before}{url}{after}"
        label = _label_for_url(before=before, hit=hit, terms=terms)
        label_lower = label.lower()
        url_lower = url.lower()
        if terms and not any(term in label_lower or term in url_lower for term in terms):
            continue
        mentions.append(
            _UrlMention(
                label=label,
                url=url,
                hit=hit,
                quote=" ".join(context.split()),
            )
        )
    return mentions


def build_qna_url_lookup_answer(
    *,
    query: str,
    hits: list[RagQueryHit],
) -> RagGroundedAnswer | None:
    if not _is_url_lookup_query(query):
        return None
    terms = _meaningful_query_terms(query)
    mentions: list[_UrlMention] = []
    seen_urls: set[str] = set()
    for hit in hits:
        for mention in _url_mentions_for_hit(hit, terms=terms):
            if mention.url in seen_urls:
                continue
            seen_urls.add(mention.url)
            mentions.append(mention)
    if not mentions:
        return None

    if len(mentions) == 1:
        text = f"{mentions[0].label} 주소는 {mentions[0].url} 입니다."
    else:
        subject = terms[0] if terms else "관련"
        text = "\n".join(
            [
                f"{subject} 관련 주소는 다음과 같습니다.",
                *[f"- {mention.label}: {mention.url}" for mention in mentions[:5]],
            ]
        )

    citations = [
        RagGroundedCitation(
            resource_id=mention.hit.resource_id,
            source_kind=mention.hit.source_kind,
            quote=mention.quote,
            locator=mention.hit.citation,
        )
        for mention in mentions[:5]
    ]
    return RagGroundedAnswer(
        text=text,
        citations=citations,
        unsupported_claims=[],
        sources_used=sorted({citation.source_kind for citation in citations}),
    )


def _with_qna_answer(
    response: RagQueryResponse,
    answer: RagGroundedAnswer,
    *,
    query_profile_flag: str,
) -> RagQueryResponse:
    return response.model_copy(
        update={
            "grounded_answer": answer,
            "sources_used": answer.sources_used,
            "query_profile": {
                **response.query_profile,
                query_profile_flag: True,
            },
        }
    )


def _as_qna_grounded_response(response: RagQueryResponse) -> RagQueryResponse:
    if response.answer_mode == RagAnswerMode.GROUNDED_ANSWER:
        return response
    return response.model_copy(update={"answer_mode": RagAnswerMode.GROUNDED_ANSWER})


def _qna_citations_from_hits(hits: list[RagQueryHit]) -> list[RagGroundedCitation]:
    citations: list[RagGroundedCitation] = []
    seen: set[tuple[str, str | None, str]] = set()
    for hit in hits:
        citation = DEFAULT_GROUNDED_ANSWER_ASSEMBLER.citation_from_hit(hit)
        key = (citation.resource_id, citation.locator, citation.quote)
        if key in seen:
            continue
        seen.add(key)
        citations.append(citation)
    return citations


def format_answer_for_history(response: RagQueryResponse) -> str:
    lines = [(response.grounded_answer.text if response.grounded_answer else "").strip()]
    if not lines[0]:
        lines[0] = ""
    evidence = _history_evidence_items(response)
    if evidence:
        lines.extend(["", "**Evidence**"])
        for index, item in enumerate(evidence[:8], start=1):
            title = _escape_markdown(item["title"])
            score = item.get("score")
            score_text = f" ({round(score * 100)}%)" if isinstance(score, (int, float)) else ""
            lines.append(f"{index}. {title}{score_text}")
    return "\n".join(lines).strip()


def _history_evidence_items(response: RagQueryResponse) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    seen: set[str] = set()
    citations = response.grounded_answer.citations if response.grounded_answer else []
    for citation in citations:
        if citation.resource_id in seen:
            continue
        seen.add(citation.resource_id)
        hit = next(
            (
                candidate
                for candidate in response.hits
                if candidate.resource_id == citation.resource_id
            ),
            None,
        )
        items.append(
            {
                "title": hit.title if hit and hit.title else citation.resource_id,
                "score": hit.score if hit else None,
            }
        )
    if items:
        return items
    for hit in response.hits:
        if hit.resource_id in seen:
            continue
        seen.add(hit.resource_id)
        items.append({"title": hit.title or hit.resource_id, "score": hit.score})
    return items


def _escape_markdown(value: str) -> str:
    return value.replace("`", "\\`").replace("*", "\\*").replace("_", "\\_").replace("~", "\\~")


def _enqueue_upsert(db: Session, doc: QnaDocument) -> None:
    partition_id = assign_default_partition(
        db,
        target=doc,
        source_namespace="qna",
        candidate_scope_kind="company",
    )
    projection_event = record_projection_event(
        db,
        resource_type=QNA_DOCUMENT_RESOURCE_TYPE,
        resource_id=doc.id,
        retrieval_partition_id=partition_id,
        change_kind="content",
        desired_state="active",
        content_checksum=doc.content_checksum,
    )
    ensure_rag_source_adapters_registered()
    enqueue_rag_sync_job(
        db,
        scope_kind=RagScopeKind.COMPANY,
        workspace_id=None,
        resource_type=QNA_DOCUMENT_RESOURCE_TYPE,
        resource_id=doc.id,
        operation=RagSyncOperation.UPSERT,
        content_checksum=doc.content_checksum,
        projection_event=projection_event,
    )


def _enqueue_delete(db: Session, *, doc: QnaDocument) -> None:
    partition_id = assign_default_partition(
        db,
        target=doc,
        source_namespace="qna",
        candidate_scope_kind="company",
    )
    projection_event = record_projection_event(
        db,
        resource_type=QNA_DOCUMENT_RESOURCE_TYPE,
        resource_id=doc.id,
        retrieval_partition_id=partition_id,
        change_kind="delete",
        desired_state="deleted",
    )
    ensure_rag_source_adapters_registered()
    enqueue_rag_sync_job(
        db,
        scope_kind=RagScopeKind.COMPANY,
        workspace_id=None,
        resource_type=QNA_DOCUMENT_RESOURCE_TYPE,
        resource_id=doc.id,
        operation=RagSyncOperation.DELETE,
        supersede_delete=True,
        projection_event=projection_event,
    )


def _read_first_qna_object(storage_keys: list[str | None]) -> bytes | None:
    for storage_key in storage_keys:
        if not storage_key:
            continue
        try:
            return read_qna_object(storage_key)
        except Exception:
            continue
    return None


def list_documents(db: Session, *, kind: str | None = None) -> list[QnaDocument]:
    stmt = select(QnaDocument).where(QnaDocument.scope_kind == QNA_SCOPE_KIND)
    if kind is not None:
        stmt = stmt.where(QnaDocument.kind == kind)
    stmt = stmt.order_by(QnaDocument.created_at.desc())
    return list(db.scalars(stmt))


def get_document(db: Session, *, document_id: str) -> QnaDocument | None:
    return db.scalar(
        select(QnaDocument).where(
            QnaDocument.id == document_id,
            QnaDocument.scope_kind == QNA_SCOPE_KIND,
        )
    )


def upload_document(
    db: Session,
    *,
    uploaded_by: User,
    filename: str,
    content: bytes,
    mime_type: str | None,
    category: str = QNA_DEFAULT_CATEGORY,
) -> QnaDocument:
    """Extract text from an admin upload and index it into the Q&A corpus.

    Raises :class:`UnsupportedDocumentType` when no extractor handles the file.
    """
    safe_filename = normalize_attachment_name(filename)
    resolved_mime = (
        mime_type or mimetypes.guess_type(safe_filename)[0] or "application/octet-stream"
    )
    body_text = _truncate(
        extract_attachment_text(
            filename=safe_filename, content=content, mime_type=resolved_mime
        ).strip()
    )
    if not body_text:
        raise UnsupportedDocumentType("no extractable text")

    checksum = _checksum(safe_filename, category, body_text)
    existing = db.scalar(
        select(QnaDocument).where(
            QnaDocument.scope_kind == QNA_SCOPE_KIND,
            QnaDocument.kind == QNA_KIND_UPLOAD,
            QnaDocument.external_id == safe_filename,
        )
    )
    doc = existing or QnaDocument(id=new_id(), scope_kind=QNA_SCOPE_KIND, kind=QNA_KIND_UPLOAD)
    assign_default_partition(
        db,
        target=doc,
        source_namespace="qna",
        candidate_scope_kind="company",
    )
    doc.scope_kind = QNA_SCOPE_KIND
    doc.workspace_id = None
    doc.external_id = safe_filename
    doc.title = safe_filename
    doc.category = category or QNA_DEFAULT_CATEGORY
    doc.body_text = body_text
    doc.char_count = len(body_text)
    doc.content_checksum = checksum
    doc.uploaded_by = uploaded_by.id
    doc.mime_type = resolved_mime
    doc.rag_status = "pending"
    doc.updated_at = utcnow_naive()
    db.add(doc)
    db.flush()
    # Persist the original file so it can be downloaded later.
    storage_key = build_company_upload_storage_key(document_id=doc.id, filename=safe_filename)
    put_qna_object(
        storage_key=storage_key,
        content=content,
        content_type=resolved_mime,
    )
    doc.storage_key = storage_key
    db.add(doc)
    _enqueue_upsert(db, doc)
    return doc


def delete_document(db: Session, *, document_id: str) -> bool:
    doc = db.scalar(
        select(QnaDocument).where(
            QnaDocument.id == document_id,
            QnaDocument.scope_kind == QNA_SCOPE_KIND,
        )
    )
    if doc is None:
        return False
    _enqueue_delete(db, doc=doc)
    db.delete(doc)
    db.flush()
    return True


def read_document_file(
    db: Session,
    *,
    document_id: str,
    filename: str,
) -> tuple[bytes, str, str] | None:
    """Return (content, content_type, filename) for a downloadable file, or None."""
    doc = db.scalar(
        select(QnaDocument).where(
            QnaDocument.id == document_id,
            QnaDocument.scope_kind == QNA_SCOPE_KIND,
        )
    )
    if doc is None:
        return None
    safe_filename = normalize_attachment_name(filename)
    if doc.kind == QNA_KIND_UPLOAD:
        if safe_filename != normalize_attachment_name(doc.external_id):
            return None
        keys = [
            doc.storage_key,
            build_company_upload_storage_key(document_id=doc.id, filename=safe_filename),
            (
                build_upload_storage_key(
                    workspace_id=doc.workspace_id,
                    document_id=doc.id,
                    filename=safe_filename,
                )
                if doc.workspace_id
                else None
            ),
        ]
        content_type = doc.mime_type or mimetypes.guess_type(filename)[0]
    else:
        attachment_names = normalize_attachment_names(doc.attachments or [])
        if safe_filename not in attachment_names:
            return None
        keys = [
            build_company_notice_attachment_storage_key(
                notice_external_id=doc.external_id,
                filename=safe_filename,
            ),
            (
                build_notice_attachment_storage_key(
                    workspace_id=doc.workspace_id,
                    notice_external_id=doc.external_id,
                    filename=safe_filename,
                )
                if doc.workspace_id
                else None
            ),
        ]
        content_type = mimetypes.guess_type(safe_filename)[0]
    content = _read_first_qna_object(keys)
    if content is None:
        return None
    return content, content_type or "application/octet-stream", safe_filename


def _notice_content_checksum(
    *,
    title: str,
    category: str,
    body_text: str,
    attachment_names: list[str],
    attachment_content_hashes: list[str] | None,
) -> str:
    """Change-detection checksum for a crawled notice.

    Includes the attachment byte-content hashes so replacing an attachment's file
    is detected even when the extracted text is unchanged (e.g. a swapped image
    whose OCR yields the same or empty text). Without this, only the extracted
    text and filenames were hashed, so a same-filename replacement with identical
    OCR output slipped through undetected.
    """
    return _checksum(
        title,
        category,
        body_text,
        sorted(attachment_names),
        sorted(attachment_content_hashes or []),
    )


def upsert_notice(
    db: Session,
    *,
    num: str,
    title: str,
    author: str | None,
    posted_at: str | None,
    body: str,
    attachments: list[str] | None,
    category: str = QNA_NOTICE_CATEGORY,
    attachment_content_hashes: list[str] | None = None,
) -> tuple[QnaDocument, bool]:
    """Idempotently store a crawled groupware notice; returns (doc, changed)."""
    body_text = _truncate(body.strip())
    attachment_names = normalize_attachment_names(attachments)
    notice_category = (category or QNA_NOTICE_CATEGORY).strip() or QNA_NOTICE_CATEGORY
    checksum = _notice_content_checksum(
        title=title,
        category=notice_category,
        body_text=body_text,
        attachment_names=attachment_names,
        attachment_content_hashes=attachment_content_hashes,
    )
    existing = db.scalar(
        select(QnaDocument).where(
            QnaDocument.scope_kind == QNA_SCOPE_KIND,
            QnaDocument.kind == QNA_KIND_NOTICE,
            QnaDocument.external_id == str(num),
        )
    )
    if (
        existing is not None
        and existing.content_checksum == checksum
        and existing.rag_status != "failed"
    ):
        if not str(existing.retrieval_partition_id or "").strip():
            _enqueue_upsert(db, existing)
        return existing, False

    doc = existing or QnaDocument(id=new_id(), scope_kind=QNA_SCOPE_KIND, kind=QNA_KIND_NOTICE)
    assign_default_partition(
        db,
        target=doc,
        source_namespace="qna",
        candidate_scope_kind="company",
    )
    doc.scope_kind = QNA_SCOPE_KIND
    doc.workspace_id = None
    doc.external_id = str(num)
    doc.title = title or f"공지 {num}"
    doc.category = notice_category
    doc.author = author
    doc.posted_at = posted_at
    doc.body_text = body_text
    doc.char_count = len(body_text)
    doc.attachments = attachment_names
    doc.content_checksum = checksum
    doc.rag_status = "pending"
    doc.updated_at = utcnow_naive()
    db.add(doc)
    db.flush()
    _enqueue_upsert(db, doc)
    return doc, True


def ask_question(
    db: Session,
    *,
    user: User,
    question: str,
    top_k: int = 20,
    conversation_id: str | None = None,
) -> RagQueryResponse:
    response = retrieval_application.query_company_qna_rag_response(
        db,
        user=user,
        query=question,
        answer_mode=RagAnswerMode("grounded-answer"),
        source_kinds=[QNA_DOC_SOURCE_KIND],
        filters={},
        top_k=top_k,
        include_binary_hits=False,
        source="api.qna.ask",
        gateway_workspace_id=rag_application.resolve_ai_gateway_workspace_id(db, user),
        conversation_id=conversation_id,
    )
    url_answer = build_qna_url_lookup_answer(query=question, hits=response.hits)
    if url_answer is not None:
        return _with_qna_answer(
            response,
            url_answer,
            query_profile_flag="qna_url_lookup_answer",
        )
    if response.query_profile.get("grounded_answer_degraded"):
        raise QnaAnswerGenerationError("Q&A grounded answer generation degraded.")
    return response


def search_question_evidence(
    db: Session,
    *,
    user: User,
    question: str,
    top_k: int = 20,
    source: str = "api.qna.ask.stream.search",
    conversation_id: str | None = None,
) -> RagQueryResponse:
    return retrieval_application.query_company_qna_rag_response(
        db,
        user=user,
        query=question,
        answer_mode=RagAnswerMode("search-only"),
        source_kinds=[QNA_DOC_SOURCE_KIND],
        filters={},
        top_k=top_k,
        include_binary_hits=False,
        source=source,
        conversation_id=conversation_id,
    )


async def stream_question_answer(
    db: Session,
    *,
    user: User,
    question: str,
    top_k: int = 20,
    conversation_id: str | None = None,
) -> AsyncIterator[QnaAnswerStreamEvent]:
    search_response = search_question_evidence(
        db,
        user=user,
        question=question,
        top_k=top_k,
        conversation_id=conversation_id,
    )
    response = _as_qna_grounded_response(search_response)
    url_answer = build_qna_url_lookup_answer(query=question, hits=response.hits)
    if url_answer is not None:
        yield QnaAnswerDelta(url_answer.text)
        yield QnaAnswerCompleted(
            _with_qna_answer(
                response,
                url_answer,
                query_profile_flag="qna_url_lookup_answer",
            )
        )
        return

    if not response.hits:
        yield QnaAnswerCompleted(response)
        return

    gateway_workspace_id = rag_application.resolve_ai_gateway_workspace_id(db, user)
    if gateway_workspace_id is None:
        raise QnaAnswerGenerationError("No active workspace is available for answer generation.")

    messages = DEFAULT_GROUNDED_ANSWER_ASSEMBLER.build_stream_messages(
        query=question,
        hits=response.hits,
    )
    chunks: list[str] = []
    finish_reason: str | None = None
    async for chunk, _decision, _config in stream_llm(
        "rag_grounded_answer",
        LlmWorkloadContext(
            workspace_id=gateway_workspace_id,
            source="api.qna.ask.stream",
            actor_user_id=user.id,
            app_id="rag",
            principal_kind="user",
            principal_id=user.id,
        ),
        db,
        messages=messages,
        stream_reasoning=False,
        context_pack=AiGatewayContextPack(
            messages=messages,
            context_strategy="rag_grounded_answer_stream_evidence",
            source_kinds=tuple(
                sorted({hit.source_kind for hit in response.hits if hit.source_kind})
            ),
            sensitivity_labels=("internal",),
            content_origin="internal_context",
        ),
        temperature=0,
        reasoning_effort="none",
        conversation_id=conversation_id,
    ):
        if chunk.kind == "content" and chunk.text:
            chunks.append(chunk.text)
            yield QnaAnswerDelta(chunk.text)
        elif chunk.kind == "done":
            finish_reason = chunk.finish_reason or "stop"

    if finish_reason not in (None, "stop"):
        raise QnaAnswerGenerationError(f"Q&A stream did not finish cleanly: {finish_reason}")

    answer_text = "".join(chunks).strip()
    if not answer_text:
        raise QnaAnswerGenerationError("Q&A stream returned an empty answer.")

    citations = _qna_citations_from_hits(response.hits)
    answer = RagGroundedAnswer(
        text=answer_text,
        citations=citations,
        unsupported_claims=[],
        sources_used=sorted({citation.source_kind for citation in citations}),
    )
    yield QnaAnswerCompleted(
        _with_qna_answer(
            response,
            answer,
            query_profile_flag="qna_streamed_answer",
        )
    )


def trigger_board_sync() -> None:
    dispatch_board_sync()


# ── RAG resource adapter hooks ──────────────────────────────────────────────
def mark_document_indexed(db: Session, *, resource_id: str, chunk_count: int) -> None:
    doc = db.get(QnaDocument, resource_id)
    if doc is None:
        return
    doc.rag_status = "indexed"
    doc.chunk_count = chunk_count
    doc.last_error = None
    doc.indexed_at = utcnow_naive()
    db.add(doc)


def mark_document_failed(db: Session, *, resource_id: str, error: str, phase: str) -> None:
    doc = db.get(QnaDocument, resource_id)
    if doc is None:
        return
    doc.rag_status = "failed"
    doc.last_error = f"[{phase}] {error}"[:2000]
    db.add(doc)
