from __future__ import annotations


DOCS_RETRIEVAL_PARTITION_ADAPTER_ID = "docs"
FILES_RETRIEVAL_PARTITION_ADAPTER_ID = "files"
LEGACY_ISSUES_RETRIEVAL_PARTITION_ADAPTER_ID = "legacy_issues"
MEETING_RETRIEVAL_PARTITION_ADAPTER_ID = "meeting"
PLANNER_RETRIEVAL_PARTITION_ADAPTER_ID = "planner"
PMS_RETRIEVAL_PARTITION_ADAPTER_ID = "pms"
QNA_RETRIEVAL_PARTITION_ADAPTER_ID = "qna"


__all__ = [
    "DOCS_RETRIEVAL_PARTITION_ADAPTER_ID",
    "FILES_RETRIEVAL_PARTITION_ADAPTER_ID",
    "LEGACY_ISSUES_RETRIEVAL_PARTITION_ADAPTER_ID",
    "MEETING_RETRIEVAL_PARTITION_ADAPTER_ID",
    "PLANNER_RETRIEVAL_PARTITION_ADAPTER_ID",
    "PMS_RETRIEVAL_PARTITION_ADAPTER_ID",
    "QNA_RETRIEVAL_PARTITION_ADAPTER_ID",
]
