import {
  BarChart3,
  BookOpen,
  Bookmark,
  Building2,
  Car,
  Home,
  LibraryBig,
  Newspaper,
  Sparkles,
  Star,
} from 'lucide-react';

import type { AppModuleManifest } from '@/src/app/shell/navigation-types';

export const newsManifest: AppModuleManifest = {
  appBarItem: { id: 'news', title: 'news', icon: Newspaper },
  surfaces: { launcher: { globalPath: '/news' } },
  contract: {
    owner: 'news-platform',
    permissions: [],
    // News content is global (same for every user), served from the global
    // /api/v1/news router — not workspace-scoped — so no workspaceApiPrefixes.
    apiDomain: 'news',
    resourceScope: 'hybrid',
    aiCapabilities: [],
    writeAuditActions: [
      'news.filter_settings.update',
      'news.fetch.trigger',
      'news.recommended.create',
      'news.recommended.delete',
      'news.scrap.create',
      'news.scrap.delete',
      'industry_report.file.upload',
      'industry_report.file.delete',
      'industry_report.fetch.trigger',
      'industry_report.recommended.create',
      'industry_report.recommended.delete',
      'industry_report.scrap.create',
      'industry_report.scrap.delete',
    ],
    appLocalTests: [
      'apps/web/src/app-modules/news/routes.spec.tsx',
      'apps/web/src/app-modules/news/views/NewsView.spec.tsx',
      'apps/api/tests/test_news.py',
      'apps/api/tests/test_industry_report.py',
    ],
  },
  defaultActiveNavItemId: 'news-home',
  navItems: [
    {
      id: 'news-home',
      title: 'news-home',
      icon: Home,
      category: 'News',
      appId: 'news',
      description: 'news-home',
      pathSuffix: '?channel=home',
    },
    {
      id: 'news-recommended',
      title: 'news-recommended',
      icon: Star,
      category: 'News',
      appId: 'news',
      description: 'news-recommended',
      pathSuffix: '?channel=recommended',
    },
    {
      id: 'news-keyword',
      title: 'news-keyword',
      icon: Newspaper,
      category: 'News',
      appId: 'news',
      description: 'news-keyword',
      pathSuffix: '?channel=keyword',
    },
    {
      id: 'news-car',
      title: 'news-car',
      icon: Car,
      category: 'News',
      appId: 'news',
      description: 'news-car',
      pathSuffix: '?channel=car',
    },
    {
      id: 'news-front',
      title: 'news-front',
      icon: Building2,
      category: 'News',
      appId: 'news',
      description: 'news-front',
      pathSuffix: '?channel=front',
    },
    {
      id: 'news-ai',
      title: 'news-ai',
      icon: Sparkles,
      category: 'News',
      appId: 'news',
      description: 'news-ai',
      pathSuffix: '?channel=ai',
    },
    {
      id: 'news-scraps',
      title: 'news-scraps',
      icon: Bookmark,
      category: 'News',
      appId: 'news',
      description: 'news-scraps',
      pathSuffix: '?channel=scraps',
    },
    {
      id: 'industry-report-trend',
      title: 'industry-report-trend',
      icon: LibraryBig,
      category: 'Industry Report',
      appId: 'news',
      pathSuffix: '?view=report&tab=trend',
    },
    {
      id: 'industry-report-autojournal',
      title: 'industry-report-autojournal',
      icon: BookOpen,
      category: 'Industry Report',
      appId: 'news',
      pathSuffix: '?view=report&tab=autojournal',
    },
    {
      id: 'industry-report-kdi',
      title: 'industry-report-kdi',
      icon: BarChart3,
      category: 'Industry Report',
      appId: 'news',
      pathSuffix: '?view=report&tab=kdi',
    },
    {
      id: 'industry-report-recommended',
      title: 'industry-report-recommended',
      icon: Star,
      category: 'Industry Report',
      appId: 'news',
      pathSuffix: '?view=report&tab=recommended',
    },
    {
      id: 'industry-report-ai',
      title: 'industry-report-ai',
      icon: Sparkles,
      category: 'Industry Report',
      appId: 'news',
      pathSuffix: '?view=report&tab=ai',
    },
    {
      id: 'industry-report-scraps',
      title: 'industry-report-scraps',
      icon: Bookmark,
      category: 'Industry Report',
      appId: 'news',
      pathSuffix: '?view=report&tab=scraps',
    },
  ],
  globalRoutePaths: ['/news', '/w/:workspaceSlug/news'],
  workspaceRoutePaths: [],
};
