"""Alembic bootstrap smoke + model-drift guard.

These tests are the C1 PR0 acceptance gate:

* ``alembic upgrade head`` against an empty Postgres reproduces the schema
  the application expects (smoke test).
* ``alembic check`` reports zero drift between SQLAlchemy models and the
  latest revision (drift guard — fails CI if a model field is added without
  a matching migration).
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect


@pytest.fixture
def alembic_config(monkeypatch: pytest.MonkeyPatch, postgres_dsn: str):
    monkeypatch.setenv("DOOWON_POSTGRES_DSN", postgres_dsn)
    monkeypatch.setenv("DOOWON_LLM_HEALTHCHECK_ON_STARTUP", "0")

    from aidoo_api.core.db import _alembic_config
    from aidoo_api.core.settings import get_settings

    get_settings.cache_clear()

    engine = create_engine(postgres_dsn)
    with engine.begin() as connection:
        connection.exec_driver_sql("DROP SCHEMA public CASCADE")
        connection.exec_driver_sql("CREATE SCHEMA public")
    engine.dispose()

    return _alembic_config()


def test_alembic_upgrade_head_creates_expected_tables(alembic_config, postgres_dsn) -> None:
    command.upgrade(alembic_config, "head")

    engine = create_engine(postgres_dsn)
    inspector = inspect(engine)
    table_names = set(inspector.get_table_names())
    engine.dispose()

    expected = {
        "users",
        "auth_sessions",
        "user_system_roles",
        "group_system_roles",
        "teams",
        "team_members",
        "pms_task_lists",
        "pms_issues",
        "pms_issue_comments",
        "pms_issue_assignees",
        "pms_issue_user_access",
        "pms_task_list_statuses",
        "pms_task_templates",
        "pms_custom_fields",
        "pms_custom_field_values",
        "pms_folders",
        "docs_native_docs",
        "docs_doc_containers",
        "docs_native_doc_pages",
        "docs_meeting_access",
        "media_files",
        "planner_events",
        "workspace_app_entitlements",
        "alembic_version",
    }
    missing = expected - table_names
    assert not missing, f"Alembic baseline did not create: {sorted(missing)}"


def test_alembic_check_reports_no_model_drift(alembic_config) -> None:
    """If a model column is added without a migration, this test must fail.

    ``alembic check`` raises ``AutogenerateDiffsDetected`` when the live
    database (just upgraded to head) does not match ``Base.metadata``.
    """
    command.upgrade(alembic_config, "head")

    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(
            "Model drift detected — SQLAlchemy models diverge from the latest "
            f"Alembic revision. Run `alembic revision --autogenerate -m <name>` "
            f"to capture the change.\n\n{exc}"
        )
