# Generated by scripts/generate-auth-realtime-contract.mjs. Do not edit.

from typing import Final

AUTH_ACCESS_CHANGED: Final = "auth.access.changed"
AUTH_ACCESS_CHANGED_REASON_APP_AVAILABILITY: Final = "app_availability"
AUTH_ACCESS_CHANGED_REASON_WORKSPACE_MEMBERSHIP: Final = "workspace_membership"
