import {
  AirVent,
  Bot,
  CarFront,
  ClipboardList,
  Code2,
  Cog,
  Cpu,
  Database,
  Fan,
  History,
  ListChecks,
  PanelTop,
  Settings,
  Thermometer,
  UserCog,
  Zap,
  Wrench,
} from 'lucide-react';

import type { AppModuleManifest } from '@/src/app/shell/navigation-types';
import {
  LEGACY_ISSUE_ASSISTANT_HISTORY_NAV_ITEM_ID,
  LEGACY_ISSUE_ASSISTANT_HISTORY_ROUTE_PATH,
  LEGACY_ISSUE_ASSISTANT_NAV_ITEM_ID,
  LEGACY_ISSUE_ASSISTANT_PATH_SUFFIX,
  LEGACY_ISSUE_ASSISTANT_ROUTE_PATH,
  LEGACY_ISSUE_COMMON_CODE_NAV_ITEM_ID,
  LEGACY_ISSUE_COMMON_CODE_PATH_SUFFIX,
  LEGACY_ISSUE_COMMON_CODE_ROUTE_PATH,
  LEGACY_ISSUE_DATASETS,
  LEGACY_ISSUE_DEFAULT_DATASET_KEY,
  LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_NAV_ITEM_ID,
  LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_PATH_SUFFIX,
  LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_ROUTE_PATH,
  LEGACY_ISSUE_FIELD_SETTINGS_NAV_ITEM_ID,
  LEGACY_ISSUE_FIELD_SETTINGS_PATH_SUFFIX,
  LEGACY_ISSUE_FIELD_SETTINGS_ROUTE_PATH,
  LEGACY_ISSUE_VEHICLE_CHECKLISTS_NAV_ITEM_ID,
  LEGACY_ISSUE_VEHICLE_CHECKLISTS_PATH_SUFFIX,
  LEGACY_ISSUE_VEHICLE_CHECKLISTS_ROUTE_PATH,
  LEGACY_ISSUE_VEHICLE_CHECKLIST_DETAIL_ROUTE_PATH,
  LEGACY_ISSUE_VEHICLE_CHECKLIST_MODULE_ROUTE_PATH,
  LEGACY_ISSUE_VEHICLE_MANAGEMENT_NAV_ITEM_ID,
  LEGACY_ISSUE_VEHICLE_MANAGEMENT_PATH_SUFFIX,
  LEGACY_ISSUE_VEHICLE_MANAGEMENT_ROUTE_PATH,
  LEGACY_ISSUE_VIEW_KEYS,
  LEGACY_ISSUE_VIEWS,
  LEGACY_ISSUE_REPORTS_PATH_SUFFIX,
  LEGACY_ISSUE_REPORTS_ROUTE_PATH,
  LEGACY_ISSUE_REPORT_DETAIL_ROUTE_PATH,
} from './core/public-api';

export const legacyIssuesManifest: AppModuleManifest = {
  appBarItem: { id: 'legacy-issues', title: 'legacy-issues', icon: History },
  contract: {
    owner: 'legacy-issues',
    permissions: [],
    apiDomain: 'legacy_issues',
    workspaceApiPrefixes: ['/api/v1/legacy-issues'],
    aiCapabilities: ['legacy_issue_assistant'],
    writeAuditActions: [
      'legacy_issues.dataset.create',
      'legacy_issues.dataset.update',
      'legacy_issues.dataset.delete',
      'legacy_issues.dataset.import',
      'legacy_issues.dataset.attachment.upload',
      'legacy_issues.dataset.attachment.delete',
      'legacy_issues.revision_meeting_attachment.upload',
      'legacy_issues.revision_meeting_attachment.description_update',
      'legacy_issues.revision_meeting_attachment.delete',
      'legacy_issues.vehicle_model.create',
      'legacy_issues.vehicle_model.update',
      'legacy_issues.vehicle_model.delete',
      'legacy_issues.vehicle_checklist_revision.create',
      'legacy_issues.vehicle_checklist.update',
      'legacy_issues.vehicle_checklist.complete',
      'legacy_issues.vehicle_module_checklist.attachment.upload',
      'legacy_issues.vehicle_module_checklist.attachment.delete',
      'legacy_issues.module_direct_editor.grant',
      'legacy_issues.module_direct_editor.revoke',
      'legacy_issues.report.share',
      'legacy_issues.report.unshare',
    ],
    appLocalTests: [
      'apps/api/tests/test_legacy_issue_assistant_reports.py',
      'apps/api/tests/test_legacy_issue_revision_meeting_attachments.py',
      'apps/web/src/app-modules/legacy-issues/core/api/legacy-issue-assistant-report-api.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/api/legacy-issue-excel-export-api.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/api/legacy-issue-direct-edit-permissions-api.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/api/legacy-issue-meeting-attachments-api.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueAssistantHistoryView.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueReportDetailView.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/LegacyIssueReportDataGrid.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/views/LegacyIssueHistoryList.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/LegacyIssueRevisionMeetingMinutes.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/legacy-issue-grid-paste-model.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/views/useLegacyIssueExcelExportJob.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/LegacyIssueExcelExportControls.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueDatasetView.refresh.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueDirectEditPermissionsView.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueVehicleChecklistView.spec.ts',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueVehicleManagementView.spec.tsx',
      'apps/web/src/app-modules/legacy-issues/core/views/CoreBusinessLegacyIssueVehicleModuleChecklistView.spec.tsx',
    ],
  },
  defaultActiveNavItemId:
    LEGACY_ISSUE_DATASETS[LEGACY_ISSUE_DEFAULT_DATASET_KEY].navItemId,
  navItems: [
    {
      id: LEGACY_ISSUE_ASSISTANT_NAV_ITEM_ID,
      title: LEGACY_ISSUE_ASSISTANT_NAV_ITEM_ID,
      icon: Bot,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_ASSISTANT_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_ASSISTANT_HISTORY_NAV_ITEM_ID,
      title: LEGACY_ISSUE_ASSISTANT_HISTORY_NAV_ITEM_ID,
      icon: History,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_REPORTS_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_NAV_ITEM_ID,
      title: LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_NAV_ITEM_ID,
      icon: UserCog,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_FIELD_SETTINGS_NAV_ITEM_ID,
      title: LEGACY_ISSUE_FIELD_SETTINGS_NAV_ITEM_ID,
      icon: Settings,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_FIELD_SETTINGS_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_COMMON_CODE_NAV_ITEM_ID,
      title: LEGACY_ISSUE_COMMON_CODE_NAV_ITEM_ID,
      icon: ListChecks,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_COMMON_CODE_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_VEHICLE_CHECKLISTS_NAV_ITEM_ID,
      title: LEGACY_ISSUE_VEHICLE_CHECKLISTS_NAV_ITEM_ID,
      icon: ClipboardList,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VEHICLE_CHECKLISTS_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_VEHICLE_MANAGEMENT_NAV_ITEM_ID,
      title: LEGACY_ISSUE_VEHICLE_MANAGEMENT_NAV_ITEM_ID,
      icon: CarFront,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VEHICLE_MANAGEMENT_PATH_SUFFIX,
    },
    {
      id: LEGACY_ISSUE_DATASETS['common-master'].navItemId,
      title: LEGACY_ISSUE_DATASETS['common-master'].navItemId,
      icon: Database,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_DATASETS['common-master'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS.aircon.navItemId,
      title: LEGACY_ISSUE_VIEWS.aircon.navItemId,
      icon: AirVent,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS.aircon.pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['heat-exchanger'].navItemId,
      title: LEGACY_ISSUE_VIEWS['heat-exchanger'].navItemId,
      icon: Thermometer,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['heat-exchanger'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['compressor-mechanical'].navItemId,
      title: LEGACY_ISSUE_VIEWS['compressor-mechanical'].navItemId,
      icon: Cog,
      category: LEGACY_ISSUE_VIEWS['compressor-mechanical'].parentNavCategoryId,
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['compressor-mechanical'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['compressor-electric'].navItemId,
      title: LEGACY_ISSUE_VIEWS['compressor-electric'].navItemId,
      icon: Zap,
      category: LEGACY_ISSUE_VIEWS['compressor-electric'].parentNavCategoryId,
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['compressor-electric'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS.interior.navItemId,
      title: LEGACY_ISSUE_VIEWS.interior.navItemId,
      icon: PanelTop,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS.interior.pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['cooling-module'].navItemId,
      title: LEGACY_ISSUE_VIEWS['cooling-module'].navItemId,
      icon: Fan,
      category: 'legacy-issues',
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['cooling-module'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['electrical-mechanical'].navItemId,
      title: LEGACY_ISSUE_VIEWS['electrical-mechanical'].navItemId,
      icon: Wrench,
      category: LEGACY_ISSUE_VIEWS['electrical-mechanical'].parentNavCategoryId,
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['electrical-mechanical'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['electrical-control-hw'].navItemId,
      title: LEGACY_ISSUE_VIEWS['electrical-control-hw'].navItemId,
      icon: Cpu,
      category: LEGACY_ISSUE_VIEWS['electrical-control-hw'].parentNavCategoryId,
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['electrical-control-hw'].pathSuffix,
    },
    {
      id: LEGACY_ISSUE_VIEWS['electrical-control-sw'].navItemId,
      title: LEGACY_ISSUE_VIEWS['electrical-control-sw'].navItemId,
      icon: Code2,
      category: LEGACY_ISSUE_VIEWS['electrical-control-sw'].parentNavCategoryId,
      appId: 'legacy-issues',
      pathSuffix: LEGACY_ISSUE_VIEWS['electrical-control-sw'].pathSuffix,
    },
  ],
  workspaceRoutePaths: [
    '/w/:workspaceSlug/legacy-issues',
    LEGACY_ISSUE_ASSISTANT_ROUTE_PATH,
    LEGACY_ISSUE_ASSISTANT_HISTORY_ROUTE_PATH,
    LEGACY_ISSUE_REPORTS_ROUTE_PATH,
    LEGACY_ISSUE_REPORT_DETAIL_ROUTE_PATH,
    LEGACY_ISSUE_DIRECT_EDIT_PERMISSIONS_ROUTE_PATH,
    LEGACY_ISSUE_FIELD_SETTINGS_ROUTE_PATH,
    LEGACY_ISSUE_COMMON_CODE_ROUTE_PATH,
    LEGACY_ISSUE_VEHICLE_CHECKLISTS_ROUTE_PATH,
    LEGACY_ISSUE_VEHICLE_CHECKLIST_DETAIL_ROUTE_PATH,
    LEGACY_ISSUE_VEHICLE_CHECKLIST_MODULE_ROUTE_PATH,
    LEGACY_ISSUE_VEHICLE_MANAGEMENT_ROUTE_PATH,
    ...LEGACY_ISSUE_VIEW_KEYS.map((key) => LEGACY_ISSUE_VIEWS[key].routePath),
  ],
};
