import {
  Activity,
  AirVent,
  AlarmClock,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  Atom,
  Award,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bell,
  Binary,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  BookText,
  Bookmark,
  Bot,
  BotMessageSquare,
  Box,
  Boxes,
  BrainCircuit,
  BrainCog,
  Briefcase,
  BriefcaseBusiness,
  Bug,
  Building,
  Building2,
  Cable,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  Car,
  ChartBarIncreasing,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumn,
  ChartSpline,
  CheckCircle2,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  ClipboardPenLine,
  ClipboardType,
  Clock,
  Clock3,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudUpload,
  Code2,
  CodeXml,
  Cog,
  Columns3,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Database,
  DatabaseBackup,
  DatabaseZap,
  Dna,
  Drill,
  Factory,
  Fan,
  FileArchive,
  FileBarChart,
  FileChartColumn,
  FileCode2,
  FileCog,
  FileJson,
  FilePenLine,
  FileSearch,
  FileSpreadsheet,
  FileStack,
  FileText,
  Files,
  Fingerprint,
  Flag,
  FlaskConical,
  FlaskRound,
  Folder,
  FolderCode,
  FolderCog,
  FolderKanban,
  FolderOpen,
  FolderSearch,
  Gauge,
  Gavel,
  Gem,
  GitBranch,
  GitPullRequest,
  Globe,
  Globe2,
  GraduationCap,
  Grid3X3,
  Hammer,
  Handshake,
  HardHat,
  Headphones,
  Heart,
  HelpCircle,
  History,
  Home,
  House,
  ImageIcon,
  Inbox,
  Info,
  KeyRound,
  LandPlot,
  Landmark,
  Languages,
  Laptop,
  LayoutDashboard,
  LayoutGrid,
  Library,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  Link,
  Link2,
  ListChecks,
  ListMusic,
  ListTodo,
  Lock,
  Mail,
  MailCheck,
  MailOpen,
  Map,
  MapPinned,
  Medal,
  Megaphone,
  MemoryStick,
  MessageCircle,
  MessageCircleQuestionMark,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Microscope,
  MonitorCog,
  Music,
  Navigation,
  Network,
  Newspaper,
  NotebookTabs,
  Package,
  Paintbrush,
  Palette,
  PanelTop,
  PanelsTopLeft,
  PenTool,
  PencilRuler,
  PieChart,
  Pin,
  Plane,
  Plug,
  PlugZap,
  Presentation,
  Puzzle,
  QrCode,
  Radar,
  Radio,
  ReceiptText,
  Rocket,
  Route,
  Rows3,
  Rss,
  Ruler,
  Satellite,
  Scale,
  ScanLine,
  ScanSearch,
  School,
  Search,
  SearchCheck,
  Send,
  Server,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Sparkle,
  Sparkles,
  SquareKanban,
  SquareTerminal,
  Star,
  Store,
  Table2,
  TableProperties,
  TabletSmartphone,
  Target,
  Terminal,
  TerminalSquare,
  TestTube,
  Timer,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  User,
  UserCog,
  Users,
  UsersRound,
  Video,
  VideoIcon,
  WandSparkles,
  Warehouse,
  Webhook,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export type AppIconPickerGroup = {
  id: string;
  iconKeys: readonly string[];
};

const APP_ICON_BY_KEY: Record<string, LucideIcon> = {
  activity: Activity,
  'air-vent': AirVent,
  'alarm-clock': AlarmClock,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  atom: Atom,
  award: Award,
  'badge-dollar-sign': BadgeDollarSign,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  binary: Binary,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  'book-text': BookText,
  bookmark: Bookmark,
  bot: Bot,
  'bot-message-square': BotMessageSquare,
  box: Box,
  boxes: Boxes,
  'brain-circuit': BrainCircuit,
  'brain-cog': BrainCog,
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  bug: Bug,
  building: Building,
  'building-2': Building2,
  cable: Cable,
  calculator: Calculator,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  car: Car,
  'chart-bar-increasing': ChartBarIncreasing,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-no-axes-column': ChartNoAxesColumn,
  'chart-spline': ChartSpline,
  'check-circle-2': CheckCircle2,
  'circle-alert': CircleAlert,
  'circle-check-big': CircleCheckBig,
  'circle-help': CircleHelp,
  'circuit-board': CircuitBoard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clipboard-pen-line': ClipboardPenLine,
  'clipboard-type': ClipboardType,
  clock: Clock,
  'clock-3': Clock3,
  cloud: Cloud,
  'cloud-cog': CloudCog,
  'cloud-download': CloudDownload,
  'cloud-upload': CloudUpload,
  'code-2': Code2,
  'code-xml': CodeXml,
  cog: Cog,
  'columns-3': Columns3,
  compass: Compass,
  contact: Contact,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  'database-backup': DatabaseBackup,
  'database-zap': DatabaseZap,
  dna: Dna,
  drill: Drill,
  factory: Factory,
  fan: Fan,
  'file-archive': FileArchive,
  'file-bar-chart': FileBarChart,
  'file-chart-column': FileChartColumn,
  'file-code-2': FileCode2,
  'file-cog': FileCog,
  'file-json': FileJson,
  'file-pen-line': FilePenLine,
  'file-search': FileSearch,
  'file-spreadsheet': FileSpreadsheet,
  'file-stack': FileStack,
  'file-text': FileText,
  files: Files,
  fingerprint: Fingerprint,
  flag: Flag,
  flask: FlaskConical,
  'flask-conical': FlaskConical,
  'flask-round': FlaskRound,
  folder: Folder,
  'folder-code': FolderCode,
  'folder-cog': FolderCog,
  'folder-kanban': FolderKanban,
  'folder-open': FolderOpen,
  'folder-search': FolderSearch,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  'git-branch': GitBranch,
  'git-pull-request': GitPullRequest,
  globe: Globe,
  'globe-2': Globe2,
  'graduation-cap': GraduationCap,
  'grid-3x3': Grid3X3,
  hammer: Hammer,
  handshake: Handshake,
  'hard-hat': HardHat,
  headphones: Headphones,
  heart: Heart,
  'help-circle': HelpCircle,
  history: History,
  home: Home,
  house: House,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  'key-round': KeyRound,
  landmark: Landmark,
  'land-plot': LandPlot,
  languages: Languages,
  laptop: Laptop,
  layout: LayoutGrid,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  library: Library,
  'library-big': LibraryBig,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  'link-2': Link2,
  'list-checks': ListChecks,
  'list-music': ListMusic,
  'list-todo': ListTodo,
  lock: Lock,
  mail: Mail,
  'mail-check': MailCheck,
  'mail-open': MailOpen,
  map: Map,
  'map-pinned': MapPinned,
  medal: Medal,
  megaphone: Megaphone,
  'memory-stick': MemoryStick,
  'message-circle': MessageCircle,
  'message-circle-question': MessageCircleQuestionMark,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  'messages-square': MessagesSquare,
  mic: Mic,
  microscope: Microscope,
  'monitor-cog': MonitorCog,
  music: Music,
  navigation: Navigation,
  network: Network,
  newspaper: Newspaper,
  'notebook-tabs': NotebookTabs,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  'panel-top': PanelTop,
  'panels-top-left': PanelsTopLeft,
  'pencil-ruler': PencilRuler,
  'pen-tool': PenTool,
  'pie-chart': PieChart,
  pin: Pin,
  plane: Plane,
  plug: Plug,
  'plug-zap': PlugZap,
  presentation: Presentation,
  puzzle: Puzzle,
  'qr-code': QrCode,
  radar: Radar,
  radio: Radio,
  'receipt-text': ReceiptText,
  rocket: Rocket,
  route: Route,
  'rows-3': Rows3,
  rss: Rss,
  ruler: Ruler,
  satellite: Satellite,
  scale: Scale,
  'scan-line': ScanLine,
  'scan-search': ScanSearch,
  school: School,
  search: Search,
  'search-check': SearchCheck,
  send: Send,
  server: Server,
  settings: Settings,
  'settings-2': Settings2,
  share: Share,
  'share-2': Share2,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  ship: Ship,
  siren: Siren,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkle: Sparkle,
  sparkles: Sparkles,
  'square-kanban': SquareKanban,
  'square-terminal': SquareTerminal,
  star: Star,
  store: Store,
  'table-2': Table2,
  'table-properties': TableProperties,
  'tablet-smartphone': TabletSmartphone,
  target: Target,
  terminal: Terminal,
  'terminal-square': TerminalSquare,
  'test-tube': TestTube,
  timer: Timer,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  user: User,
  'user-cog': UserCog,
  users: Users,
  'users-round': UsersRound,
  video: Video,
  'video-icon': VideoIcon,
  'wand-sparkles': WandSparkles,
  warehouse: Warehouse,
  webhook: Webhook,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export const APP_ICON_KEYS: readonly string[] = Object.freeze(
  Object.keys(APP_ICON_BY_KEY).sort((left, right) => left.localeCompare(right)),
);

export const APP_ICON_PICKER_GROUPS: readonly AppIconPickerGroup[] =
  Object.freeze([
    {
      id: 'featured',
      iconKeys: [
        'layout',
        'sparkles',
        'users',
        'briefcase',
        'star',
        'settings',
        'search',
        'folder-kanban',
        'database',
        'flask-conical',
        'shield-check',
        'chart-line',
      ],
    },
    {
      id: 'lab',
      iconKeys: [
        'flask',
        'flask-conical',
        'flask-round',
        'test-tube',
        'microscope',
        'atom',
        'dna',
        'bug',
        'scan-search',
        'search-check',
        'activity',
        'zap',
        'lightbulb',
      ],
    },
    {
      id: 'aiData',
      iconKeys: [
        'sparkles',
        'sparkle',
        'wand-sparkles',
        'brain-circuit',
        'brain-cog',
        'bot',
        'bot-message-square',
        'database',
        'database-zap',
        'database-backup',
        'binary',
        'circuit-board',
        'network',
        'cpu',
        'memory-stick',
        'server',
        'cloud',
        'cloud-cog',
      ],
    },
    {
      id: 'work',
      iconKeys: [
        'briefcase',
        'briefcase-business',
        'clipboard-list',
        'clipboard-check',
        'clipboard-pen-line',
        'clipboard-type',
        'list-checks',
        'list-todo',
        'square-kanban',
        'folder-kanban',
        'workflow',
        'calendar',
        'calendar-days',
        'calendar-clock',
        'clock',
        'clock-3',
        'timer',
        'alarm-clock',
      ],
    },
    {
      id: 'collaboration',
      iconKeys: [
        'users',
        'users-round',
        'user',
        'user-cog',
        'contact',
        'messages-square',
        'message-square',
        'message-square-text',
        'message-circle',
        'message-circle-question',
        'mail',
        'mail-open',
        'mail-check',
        'inbox',
        'send',
        'share',
        'share-2',
        'handshake',
      ],
    },
    {
      id: 'docsKnowledge',
      iconKeys: [
        'files',
        'file-text',
        'file-search',
        'file-pen-line',
        'file-bar-chart',
        'file-chart-column',
        'file-spreadsheet',
        'file-code-2',
        'file-json',
        'file-archive',
        'file-stack',
        'file-cog',
        'book-open',
        'book-open-check',
        'book-marked',
        'book-text',
        'notebook-tabs',
        'library',
        'library-big',
        'graduation-cap',
        'school',
        'languages',
        'newspaper',
        'rss',
      ],
    },
    {
      id: 'operations',
      iconKeys: [
        'settings',
        'settings-2',
        'cog',
        'sliders-horizontal',
        'gauge',
        'monitor-cog',
        'wrench',
        'hammer',
        'drill',
        'hard-hat',
        'factory',
        'warehouse',
        'truck',
        'ship',
        'plane',
        'car',
        'route',
        'map',
        'map-pinned',
        'navigation',
        'compass',
        'air-vent',
        'fan',
        'cable',
        'plug',
        'plug-zap',
      ],
    },
    {
      id: 'securityLegal',
      iconKeys: [
        'shield',
        'shield-check',
        'shield-alert',
        'key-round',
        'fingerprint',
        'lock',
        'siren',
        'scale',
        'gavel',
        'landmark',
        'book-open-check',
        'circle-alert',
        'triangle-alert',
        'alert-triangle',
      ],
    },
    {
      id: 'analyticsFinance',
      iconKeys: [
        'bar-chart-3',
        'chart-line',
        'chart-spline',
        'chart-column',
        'chart-no-axes-column',
        'chart-bar-increasing',
        'pie-chart',
        'trending-up',
        'target',
        'trophy',
        'medal',
        'award',
        'banknote',
        'receipt-text',
        'calculator',
        'credit-card',
        'badge-dollar-sign',
        'gem',
      ],
    },
    {
      id: 'development',
      iconKeys: [
        'code-2',
        'code-xml',
        'terminal',
        'terminal-square',
        'square-terminal',
        'file-code-2',
        'folder-code',
        'folder-cog',
        'git-branch',
        'git-pull-request',
        'webhook',
        'qr-code',
        'scan-line',
        'laptop',
        'smartphone',
        'tablet-smartphone',
        'cloud-upload',
        'cloud-download',
        'panels-top-left',
        'layout-dashboard',
        'layout-grid',
        'grid-3x3',
        'table-2',
        'table-properties',
        'rows-3',
        'columns-3',
      ],
    },
    {
      id: 'mediaDesign',
      iconKeys: [
        'image',
        'video',
        'video-icon',
        'music',
        'radio',
        'mic',
        'list-music',
        'presentation',
        'palette',
        'paintbrush',
        'pen-tool',
        'pencil-ruler',
        'ruler',
      ],
    },
    {
      id: 'general',
      iconKeys: [
        'home',
        'house',
        'building',
        'building-2',
        'store',
        'globe',
        'globe-2',
        'help-circle',
        'circle-help',
        'info',
        'bell',
        'megaphone',
        'headphones',
        'life-buoy',
        'archive',
        'archive-restore',
        'box',
        'boxes',
        'package',
        'bookmark',
        'flag',
        'pin',
        'heart',
        'panel-top',
        'folder',
        'folder-open',
        'folder-search',
        'link',
        'link-2',
        'puzzle',
        'land-plot',
        'radar',
        'rocket',
        'satellite',
      ],
    },
  ]);

export function appIconForKey(iconKey: string): LucideIcon {
  return APP_ICON_BY_KEY[iconKey] ?? LayoutGrid;
}
