import { act, cleanup, render } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { AgentTerminalSurface } from './AgentTerminalSurface';

type DataListener = (data: string) => void;

const terminalHarness = vi.hoisted(() => ({
  instances: [] as Array<{
    emitData: (data: string) => void;
    writes: string[];
  }>,
}));

vi.mock('@xterm/addon-fit', () => ({
  FitAddon: class {
    fit = vi.fn();
  },
}));

vi.mock('@xterm/xterm', () => ({
  Terminal: class {
    cols = 80;
    rows = 24;
    writes: string[] = [];
    private dataListener: DataListener | null = null;

    constructor() {
      terminalHarness.instances.push(this);
    }

    dispose() {}
    focus() {}
    loadAddon() {}
    open() {}

    onData(listener: DataListener) {
      this.dataListener = listener;
      return { dispose: () => (this.dataListener = null) };
    }

    emitData(data: string) {
      this.dataListener?.(data);
    }

    write(data: Uint8Array | string, callback?: () => void) {
      const text =
        typeof data === 'string' ? data : new TextDecoder().decode(data);
      this.writes.push(text);
      if (text.includes('\u001b[>c')) {
        this.dataListener?.('\u001b[>0;276;0c');
      }
      callback?.();
    }
  },
}));

class FakeWebSocket extends EventTarget {
  static readonly CONNECTING = 0;
  static readonly OPEN = 1;
  static readonly CLOSING = 2;
  static readonly CLOSED = 3;
  static instances: FakeWebSocket[] = [];

  readonly sent: string[] = [];
  readonly url: string;
  readyState = FakeWebSocket.CONNECTING;

  constructor(url: string | URL) {
    super();
    this.url = String(url);
    FakeWebSocket.instances.push(this);
  }

  close(code = 1000) {
    this.readyState = FakeWebSocket.CLOSED;
    const event = new Event('close');
    Object.defineProperty(event, 'code', { value: code });
    this.dispatchEvent(event);
  }

  open() {
    this.readyState = FakeWebSocket.OPEN;
    this.dispatchEvent(new Event('open'));
  }

  receive(payload: object) {
    this.dispatchEvent(
      new MessageEvent('message', { data: JSON.stringify(payload) }),
    );
  }

  send(data: string) {
    this.sent.push(data);
  }
}

function encode(value: string): string {
  return window.btoa(value);
}

function inputFrames(socket: FakeWebSocket) {
  return socket.sent
    .map((frame) => JSON.parse(frame) as { type?: string; data?: string })
    .filter((frame) => frame.type === 'input');
}

beforeEach(() => {
  terminalHarness.instances.length = 0;
  FakeWebSocket.instances.length = 0;
  vi.stubGlobal('WebSocket', FakeWebSocket);
  vi.stubGlobal(
    'ResizeObserver',
    class {
      disconnect() {}
      observe() {}
      unobserve() {}
    },
  );
  vi.stubGlobal('requestAnimationFrame', (callback: FrameRequestCallback) => {
    callback(0);
    return 1;
  });
  vi.stubGlobal('cancelAnimationFrame', () => undefined);
});

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe('AgentTerminalSurface replay handling', () => {
  it('does not echo terminal protocol responses generated by replayed output', () => {
    render(
      <AgentTerminalSurface
        ariaLabel="terminal"
        onConnectionStateChange={vi.fn()}
        onError={vi.fn()}
        onExit={vi.fn()}
        sessionId="session-1"
        token="token-1"
      />,
    );

    const socket = FakeWebSocket.instances[0];
    const terminal = terminalHarness.instances[0];
    expect(socket).toBeDefined();
    expect(terminal).toBeDefined();

    act(() => socket?.open());
    act(() => socket?.receive({ type: 'ready', active: true }));
    if (!socket || !terminal)
      throw new Error('terminal harness did not initialize');
    socket.sent.length = 0;

    act(() =>
      socket.receive({
        type: 'replay',
        data: encode('\u001b[>c'),
      }),
    );

    expect(terminal.writes).toEqual(['\u001b[>c']);
    expect(inputFrames(socket)).toEqual([]);

    act(() =>
      socket.receive({
        type: 'output',
        data: encode('\u001b[>c'),
      }),
    );

    expect(inputFrames(socket)).toHaveLength(1);
    expect(window.atob(inputFrames(socket)[0]?.data ?? '')).toBe(
      '\u001b[>0;276;0c',
    );

    socket.sent.length = 0;
    act(() => terminal.emitData('a'));
    expect(window.atob(inputFrames(socket)[0]?.data ?? '')).toBe('a');
  });
});
