import { act, cleanup, render } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { AgentTerminalSurface } from './AgentTerminalSurface';

type DataListener = (data: string) => void;
type WheelListener = (event: WheelEvent) => boolean;

const terminalHarness = vi.hoisted(() => ({
  instances: [] as Array<{
    emitData: (data: string) => void;
    emitWheel: (event: WheelEvent) => boolean | undefined;
    options: {
      theme?: {
        selectionBackground?: string;
        selectionForeground?: string;
        selectionInactiveBackground?: string;
      };
    };
    writes: string[];
  }>,
}));

vi.mock('@xterm/addon-fit', () => ({
  FitAddon: class {
    fit = vi.fn();
  },
}));

vi.mock('@xterm/xterm', () => ({
  Terminal: class {
    cols = 80;
    rows = 24;
    writes: string[] = [];
    private dataListener: DataListener | null = null;
    private wheelListener: WheelListener | null = null;

    constructor(
      readonly options: {
        theme?: {
          selectionBackground?: string;
          selectionForeground?: string;
          selectionInactiveBackground?: string;
        };
      },
    ) {
      terminalHarness.instances.push(this);
    }

    dispose = vi.fn();
    focus = vi.fn();
    loadAddon = vi.fn();
    open = vi.fn();

    onData(listener: DataListener) {
      this.dataListener = listener;
      return { dispose: () => (this.dataListener = null) };
    }

    attachCustomWheelEventHandler(listener: WheelListener) {
      this.wheelListener = listener;
    }

    emitData(data: string) {
      this.dataListener?.(data);
    }

    emitWheel(event: WheelEvent) {
      return this.wheelListener?.(event);
    }

    write(data: Uint8Array | string, callback?: () => void) {
      const text =
        typeof data === 'string' ? data : new TextDecoder().decode(data);
      this.writes.push(text);
      if (text.includes('\u001b[>c')) {
        this.dataListener?.('\u001b[>0;276;0c');
      }
      callback?.();
    }
  },
}));

class FakeWebSocket extends EventTarget {
  static readonly CONNECTING = 0;
  static readonly OPEN = 1;
  static readonly CLOSING = 2;
  static readonly CLOSED = 3;
  static instances: FakeWebSocket[] = [];

  readonly sent: string[] = [];
  readonly url: string;
  readyState = FakeWebSocket.CONNECTING;

  constructor(url: string | URL) {
    super();
    this.url = String(url);
    FakeWebSocket.instances.push(this);
  }

  close(code = 1000) {
    this.readyState = FakeWebSocket.CLOSED;
    const event = new Event('close');
    Object.defineProperty(event, 'code', { value: code });
    this.dispatchEvent(event);
  }

  open() {
    this.readyState = FakeWebSocket.OPEN;
    this.dispatchEvent(new Event('open'));
  }

  receive(payload: object) {
    this.dispatchEvent(
      new MessageEvent('message', { data: JSON.stringify(payload) }),
    );
  }

  send(data: string) {
    this.sent.push(data);
  }
}

function encode(value: string): string {
  return window.btoa(value);
}

function inputFrames(socket: FakeWebSocket) {
  return socket.sent
    .map((frame) => JSON.parse(frame) as { type?: string; data?: string })
    .filter((frame) => frame.type === 'input');
}

beforeEach(() => {
  terminalHarness.instances.length = 0;
  FakeWebSocket.instances.length = 0;
  vi.stubGlobal('WebSocket', FakeWebSocket);
  vi.stubGlobal(
    'ResizeObserver',
    class {
      disconnect = vi.fn();
      observe = vi.fn();
      unobserve = vi.fn();
    },
  );
  vi.stubGlobal('requestAnimationFrame', (callback: FrameRequestCallback) => {
    callback(0);
    return 1;
  });
  vi.stubGlobal('cancelAnimationFrame', () => undefined);
});

afterEach(() => {
  cleanup();
  vi.useRealTimers();
  vi.unstubAllGlobals();
});

describe('AgentTerminalSurface replay handling', () => {
  it('uses contrasting terminal selection colors in dark mode', () => {
    render(
      <AgentTerminalSurface
        ariaLabel="terminal"
        onConnectionStateChange={vi.fn()}
        onError={vi.fn()}
        onExit={vi.fn()}
        sessionId="session-theme"
        token="token-1"
      />,
    );

    expect(terminalHarness.instances[0]?.options.theme).toMatchObject({
      selectionBackground: '#1d4ed8',
      selectionForeground: '#ffffff',
      selectionInactiveBackground: '#1e40af',
    });
  });

  it('does not echo terminal protocol responses generated by replayed output', () => {
    render(
      <AgentTerminalSurface
        ariaLabel="terminal"
        onConnectionStateChange={vi.fn()}
        onError={vi.fn()}
        onExit={vi.fn()}
        sessionId="session-1"
        token="token-1"
      />,
    );

    const socket = FakeWebSocket.instances[0];
    const terminal = terminalHarness.instances[0];
    expect(socket).toBeDefined();
    expect(terminal).toBeDefined();

    act(() => socket?.open());
    act(() => socket?.receive({ type: 'ready', active: true }));
    if (!socket || !terminal)
      throw new Error('terminal harness did not initialize');
    socket.sent.length = 0;

    act(() =>
      socket.receive({
        type: 'replay',
        data: encode('\u001b[>c'),
      }),
    );

    expect(terminal.writes).toEqual(['\u001b[>c']);
    expect(inputFrames(socket)).toEqual([]);

    act(() =>
      socket.receive({
        type: 'output',
        data: encode('\u001b[>c'),
      }),
    );

    expect(inputFrames(socket)).toHaveLength(1);
    expect(window.atob(inputFrames(socket)[0]?.data ?? '')).toBe(
      '\u001b[>0;276;0c',
    );

    socket.sent.length = 0;
    act(() => terminal.emitData('a'));
    expect(window.atob(inputFrames(socket)[0]?.data ?? '')).toBe('a');
  });

  it('routes wheel movement to tmux scrollback instead of prompt history', () => {
    vi.useFakeTimers();
    render(
      <AgentTerminalSurface
        ariaLabel="terminal"
        onConnectionStateChange={vi.fn()}
        onError={vi.fn()}
        onExit={vi.fn()}
        sessionId="session-scroll"
        token="token-1"
      />,
    );

    const socket = FakeWebSocket.instances[0];
    const terminal = terminalHarness.instances[0];
    expect(socket).toBeDefined();
    expect(terminal).toBeDefined();
    if (!socket || !terminal)
      throw new Error('terminal harness did not initialize');

    act(() => socket.open());
    act(() => socket.receive({ type: 'ready', active: true }));
    socket.sent.length = 0;

    const wheelEvent = new WheelEvent('wheel', {
      cancelable: true,
      deltaMode: WheelEvent.DOM_DELTA_PIXEL,
      deltaY: -96,
    });
    expect(terminal.emitWheel(wheelEvent)).toBe(false);
    expect(wheelEvent.defaultPrevented).toBe(true);
    expect(inputFrames(socket)).toEqual([]);

    act(() => vi.advanceTimersByTime(32));
    expect(socket.sent.map((frame) => JSON.parse(frame))).toEqual([
      { type: 'scroll', lines: -3 },
    ]);

    act(() => terminal.emitData('a'));
    expect(socket.sent.map((frame) => JSON.parse(frame))).toEqual([
      { type: 'scroll', lines: -3 },
      { type: 'scroll_end' },
      { type: 'input', data: encode('a') },
    ]);

    socket.sent.length = 0;
    terminal.emitWheel(
      new WheelEvent('wheel', {
        cancelable: true,
        deltaMode: WheelEvent.DOM_DELTA_PIXEL,
        deltaY: -96,
      }),
    );
    act(() => terminal.emitData('b'));
    act(() => vi.advanceTimersByTime(32));
    expect(socket.sent.map((frame) => JSON.parse(frame))).toEqual([
      { type: 'input', data: encode('b') },
    ]);
  });
});
