from __future__ import annotations


LEGACY_ISSUE_ASSISTANT_TASK_KIND = "legacy_issue_assistant"
LEGACY_ISSUE_CONVERSATION_ANSWER_TASK_KIND = "legacy_issue_conversation_answer"
LEGACY_ISSUE_CONVERSATION_ANSWER_WORKLOAD_ID = "legacy_issues.conversation_answer"
LEGACY_ISSUE_INTENT_ROUTER_TASK_KIND = "legacy_issue_intent_router"
LEGACY_ISSUE_INTENT_ROUTER_WORKLOAD_ID = "legacy_issues.intent_router"
LEGACY_ISSUE_ANALYSIS_PLAN_TASK_KIND = "legacy_issue_analysis_plan"
LEGACY_ISSUE_ANALYSIS_PLAN_WORKLOAD_ID = "legacy_issues.analysis_plan"
LEGACY_ISSUE_ANALYSIS_SQL_FALLBACK_TASK_KIND = "legacy_issue_analysis_sql_fallback"
LEGACY_ISSUE_ANALYSIS_SQL_FALLBACK_WORKLOAD_ID = "legacy_issues.analysis_sql_fallback"
LEGACY_ISSUE_SQL_AGENT_TASK_KIND = "legacy_issue_sql_agent"
LEGACY_ISSUE_SQL_AGENT_WORKLOAD_ID = "legacy_issues.sql_agent"
LEGACY_ISSUE_REQUEST_INTERPRET_TASK_KIND = "legacy_issue_request_interpret"
LEGACY_ISSUE_REQUEST_INTERPRET_WORKLOAD_ID = "legacy_issues.request_interpret"
LEGACY_ISSUE_REPORT_TEMPLATE_TASK_KIND = "legacy_issue_report_template"
LEGACY_ISSUE_REPORT_TEMPLATE_WORKLOAD_ID = "legacy_issues.report_template"
LEGACY_ISSUE_QUANTITATIVE_ANALYST_TASK_KIND = "legacy_issue_quantitative_analyst"
LEGACY_ISSUE_QUANTITATIVE_ANALYST_WORKLOAD_ID = (
    "legacy_issues.quantitative_analyst"
)
LEGACY_ISSUE_EVIDENCE_ANALYST_TASK_KIND = "legacy_issue_evidence_analyst"
LEGACY_ISSUE_EVIDENCE_ANALYST_WORKLOAD_ID = "legacy_issues.evidence_analyst"
LEGACY_ISSUE_CHECKLIST_ANALYST_TASK_KIND = "legacy_issue_checklist_analyst"
LEGACY_ISSUE_CHECKLIST_ANALYST_WORKLOAD_ID = "legacy_issues.checklist_analyst"
LEGACY_ISSUE_REPORT_DRAFT_TASK_KIND = "legacy_issue_report_draft"
LEGACY_ISSUE_REPORT_DRAFT_WORKLOAD_ID = "legacy_issues.report_draft"
LEGACY_ISSUE_GROUNDING_REVIEW_TASK_KIND = "legacy_issue_grounding_review"
LEGACY_ISSUE_GROUNDING_REVIEW_WORKLOAD_ID = "legacy_issues.grounding_review"
LEGACY_ISSUE_REPORT_FINALIZE_TASK_KIND = "legacy_issue_report_finalize"
LEGACY_ISSUE_REPORT_FINALIZE_WORKLOAD_ID = "legacy_issues.report_finalize"
LEGACY_ISSUE_REPORT_CORRECTION_TASK_KIND = "legacy_issue_report_correction"
LEGACY_ISSUE_REPORT_CORRECTION_WORKLOAD_ID = "legacy_issues.report_correction"
LEGACY_ISSUE_ANSWER_DRAFT_TASK_KIND = "legacy_issue_answer_draft"
LEGACY_ISSUE_ANSWER_DRAFT_WORKLOAD_ID = "legacy_issues.answer_draft"
LEGACY_ISSUE_ATTACHMENT_SUMMARY_TASK_KIND = "legacy_issue_attachment_summary"
LEGACY_ISSUE_ATTACHMENT_VISION_TASK_KIND = "legacy_issue_attachment_vision"


__all__ = [
    "LEGACY_ISSUE_ASSISTANT_TASK_KIND",
    "LEGACY_ISSUE_CONVERSATION_ANSWER_TASK_KIND",
    "LEGACY_ISSUE_CONVERSATION_ANSWER_WORKLOAD_ID",
    "LEGACY_ISSUE_INTENT_ROUTER_TASK_KIND",
    "LEGACY_ISSUE_INTENT_ROUTER_WORKLOAD_ID",
    "LEGACY_ISSUE_ANALYSIS_PLAN_TASK_KIND",
    "LEGACY_ISSUE_ANALYSIS_PLAN_WORKLOAD_ID",
    "LEGACY_ISSUE_ANALYSIS_SQL_FALLBACK_TASK_KIND",
    "LEGACY_ISSUE_ANALYSIS_SQL_FALLBACK_WORKLOAD_ID",
    "LEGACY_ISSUE_ANSWER_DRAFT_TASK_KIND",
    "LEGACY_ISSUE_ANSWER_DRAFT_WORKLOAD_ID",
    "LEGACY_ISSUE_ATTACHMENT_SUMMARY_TASK_KIND",
    "LEGACY_ISSUE_ATTACHMENT_VISION_TASK_KIND",
    "LEGACY_ISSUE_CHECKLIST_ANALYST_TASK_KIND",
    "LEGACY_ISSUE_CHECKLIST_ANALYST_WORKLOAD_ID",
    "LEGACY_ISSUE_EVIDENCE_ANALYST_TASK_KIND",
    "LEGACY_ISSUE_EVIDENCE_ANALYST_WORKLOAD_ID",
    "LEGACY_ISSUE_GROUNDING_REVIEW_TASK_KIND",
    "LEGACY_ISSUE_GROUNDING_REVIEW_WORKLOAD_ID",
    "LEGACY_ISSUE_QUANTITATIVE_ANALYST_TASK_KIND",
    "LEGACY_ISSUE_QUANTITATIVE_ANALYST_WORKLOAD_ID",
    "LEGACY_ISSUE_REPORT_CORRECTION_TASK_KIND",
    "LEGACY_ISSUE_REPORT_CORRECTION_WORKLOAD_ID",
    "LEGACY_ISSUE_REPORT_DRAFT_TASK_KIND",
    "LEGACY_ISSUE_REPORT_DRAFT_WORKLOAD_ID",
    "LEGACY_ISSUE_REPORT_FINALIZE_TASK_KIND",
    "LEGACY_ISSUE_REPORT_FINALIZE_WORKLOAD_ID",
    "LEGACY_ISSUE_REPORT_TEMPLATE_TASK_KIND",
    "LEGACY_ISSUE_REPORT_TEMPLATE_WORKLOAD_ID",
    "LEGACY_ISSUE_REQUEST_INTERPRET_TASK_KIND",
    "LEGACY_ISSUE_REQUEST_INTERPRET_WORKLOAD_ID",
    "LEGACY_ISSUE_SQL_AGENT_TASK_KIND",
    "LEGACY_ISSUE_SQL_AGENT_WORKLOAD_ID",
]
