// Generated by scripts/generate-auth-realtime-contract.mjs. Do not edit.

export const AUTH_REALTIME_EVENT_TYPES = {
  accessChanged: "auth.access.changed",
} as const;

export const AUTH_ACCESS_CHANGE_REASONS = {
  appAvailability: "app_availability",
  workspaceMembership: "workspace_membership",
} as const;
