import {
  Activity,
  AppWindow,
  BarChart3,
  BrainCircuit,
  Building2,
  Database,
  FileSearch,
  KeyRound,
  MessagesSquare,
  Server,
  Settings,
  ShieldCheck,
  User,
  Wrench,
} from 'lucide-react';

import type { AppModuleManifest } from '@/src/app/shell/navigation-types';

export const settingsManifest: AppModuleManifest = {
  appBarItem: { id: 'settings', title: 'settings', icon: Settings },
  contract: {
    owner: 'platform-admin',
    permissions: [
      'admin.access',
      'user.read',
      'organization.read',
      'platform_api_key.read',
      'group.read',
      'app.access_policy.read',
      'audit.read',
    ],
    apiDomain: 'auth',
    aiCapabilities: [],
    writeAuditActions: [
      'auth.update-preferences',
      'auth.revoke-session',
      'community.channel.create',
      'community.channel.update',
      'community.channel.delete',
      'admin.organization_unit.create',
      'admin.organization_unit.update',
      'admin.hermes.research_source.update',
      'admin.platform_api_key.issue',
      'admin.platform_api_key.reveal',
      'admin.platform_api_key.revoke',
    ],
    appLocalTests: [
      'apps/web/src/app/shell/app-registry.spec.ts',
      'apps/web/src/app-modules/settings/routes.spec.ts',
      'apps/api/tests/test_company_groups.py',
    ],
  },
  defaultActiveNavItemId: 'settings-general',
  navItems: [
    {
      id: 'settings-general',
      title: 'settings-general',
      icon: Settings,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/general',
    },
    {
      id: 'settings-people',
      title: 'settings-people',
      icon: User,
      category: 'Organization',
      appId: 'settings',
      absolutePath: '/admin/people',
    },
    {
      id: 'settings-organization',
      title: 'settings-organization',
      icon: Building2,
      category: 'Organization',
      appId: 'settings',
      absolutePath: '/admin/organization',
    },
    {
      id: 'settings-api-integrations',
      title: 'settings-api-integrations',
      icon: KeyRound,
      category: 'SecurityAudit',
      appId: 'settings',
      absolutePath: '/admin/api-integrations',
    },
    {
      id: 'settings-apps-access',
      title: 'settings-apps-access',
      icon: AppWindow,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/apps/access',
    },
    {
      id: 'settings-apps-app-bar',
      title: 'settings-apps-app-bar',
      icon: Settings,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/apps/app-bar',
    },
    {
      id: 'settings-llm',
      title: 'settings-llm',
      icon: BrainCircuit,
      category: 'AIPlatform',
      appId: 'settings',
      absolutePath: '/admin/llm',
    },
    {
      id: 'settings-ai-tools',
      title: 'settings-ai-tools',
      icon: Wrench,
      category: 'AIPlatform',
      appId: 'settings',
      absolutePath: '/admin/ai-tools',
    },
    {
      id: 'settings-model-monitoring',
      title: 'settings-model-monitoring',
      icon: Server,
      category: 'Operations',
      appId: 'settings',
      absolutePath: '/admin/model-monitoring',
    },
    {
      id: 'settings-document-processing',
      title: 'settings-document-processing',
      icon: FileSearch,
      category: 'AIPlatform',
      appId: 'settings',
      absolutePath: '/admin/document-processing',
    },
    {
      id: 'settings-ai-security',
      title: 'settings-ai-security',
      icon: ShieldCheck,
      category: 'SecurityAudit',
      appId: 'settings',
      absolutePath: '/admin/ai-security',
    },
    {
      id: 'settings-groups',
      title: 'settings-groups',
      icon: Database,
      category: 'Organization',
      appId: 'settings',
      absolutePath: '/admin/groups',
    },
    {
      id: 'settings-community',
      title: 'settings-community',
      icon: MessagesSquare,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/community',
    },
    {
      id: 'settings-usage',
      title: 'settings-usage',
      icon: BarChart3,
      category: 'Operations',
      appId: 'settings',
      absolutePath: '/admin/usage',
    },
    {
      id: 'settings-audit',
      title: 'settings-audit',
      icon: Activity,
      category: 'SecurityAudit',
      appId: 'settings',
      absolutePath: '/admin/audit',
    },
  ],
  appRoutePaths: [],
  staticAppRoutePaths: [],
  globalRoutePaths: [],
  staticGlobalRoutePaths: [
    '/admin',
    '/admin/general',
    '/admin/people',
    '/admin/organization',
    '/admin/api-integrations',
    '/admin/apps/access',
    '/admin/apps/app-bar',
    '/admin/llm',
    '/admin/ai-tools',
    '/admin/model-monitoring',
    '/admin/document-processing',
    '/admin/ai-security',
    '/admin/groups',
    '/admin/community',
    '/admin/usage',
    '/admin/audit',
  ],
};
