import {
  Activity,
  AppWindow,
  BarChart3,
  BrainCircuit,
  Clock3,
  Database,
  FileSearch,
  IdCard,
  KeyRound,
  MessagesSquare,
  Server,
  Settings,
  ShieldCheck,
  User,
} from 'lucide-react';

import type { AppModuleManifest } from '@/src/app/shell/navigation-types';

export const settingsManifest: AppModuleManifest = {
  appBarItem: { id: 'settings', title: 'settings', icon: Settings },
  contract: {
    owner: 'platform-admin',
    permissions: [
      'admin.access',
      'user.read',
      'workspace.read',
      'team.read',
      'audit.read',
    ],
    apiDomain: 'auth',
    aiCapabilities: [],
    writeAuditActions: [
      'auth.update-preferences',
      'auth.revoke-session',
      'community.channel.create',
      'community.channel.update',
      'community.channel.delete',
    ],
    appLocalTests: [
      'apps/web/src/app/shell/app-registry.spec.ts',
      'apps/web/src/app-modules/settings/routes.spec.ts',
      'apps/api/tests/test_admin_workspaces.py',
    ],
  },
  defaultActiveNavItemId: 'settings-general',
  navItems: [
    {
      id: 'settings-general',
      title: 'settings-general',
      icon: Settings,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/general',
    },
    {
      id: 'settings-people',
      title: 'settings-people',
      icon: User,
      category: 'Organization',
      appId: 'settings',
      absolutePath: '/admin/people',
    },
    {
      id: 'settings-hr',
      title: 'settings-hr',
      icon: IdCard,
      category: 'Organization',
      appId: 'settings',
      absolutePath: '/admin/hr',
    },
    {
      id: 'settings-apps-platform',
      title: 'settings-apps-platform',
      icon: AppWindow,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/apps/platform',
    },
    {
      id: 'settings-apps-workspace',
      title: 'settings-apps-workspace',
      icon: Database,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/apps/workspace',
    },
    {
      id: 'settings-apps-app-bar',
      title: 'settings-apps-app-bar',
      icon: Settings,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/apps/app-bar',
    },
    {
      id: 'settings-llm',
      title: 'settings-llm',
      icon: BrainCircuit,
      category: 'AIPlatform',
      appId: 'settings',
      absolutePath: '/admin/llm',
    },
    {
      id: 'settings-model-monitoring',
      title: 'settings-model-monitoring',
      icon: Server,
      category: 'Operations',
      appId: 'settings',
      absolutePath: '/admin/model-monitoring',
    },
    {
      id: 'settings-document-processing',
      title: 'settings-document-processing',
      icon: FileSearch,
      category: 'AIPlatform',
      appId: 'settings',
      absolutePath: '/admin/document-processing',
    },
    {
      id: 'settings-ai-security',
      title: 'settings-ai-security',
      icon: ShieldCheck,
      category: 'SecurityAudit',
      appId: 'settings',
      absolutePath: '/admin/ai-security',
    },
    {
      id: 'settings-workspaces',
      title: 'settings-workspaces',
      icon: Database,
      category: 'Organization',
      appId: 'settings',
      absolutePath: '/admin/workspaces',
    },
    {
      id: 'settings-community',
      title: 'settings-community',
      icon: MessagesSquare,
      category: 'Platform',
      appId: 'settings',
      absolutePath: '/admin/community',
    },
    {
      id: 'settings-api-keys',
      title: 'settings-api-keys',
      icon: KeyRound,
      category: 'SecurityAudit',
      appId: 'settings',
      absolutePath: '/admin/api-keys',
    },
    {
      id: 'settings-batches',
      title: 'settings-batches',
      icon: Clock3,
      category: 'Operations',
      appId: 'settings',
      absolutePath: '/admin/batches',
    },
    {
      id: 'settings-usage',
      title: 'settings-usage',
      icon: BarChart3,
      category: 'Operations',
      appId: 'settings',
      absolutePath: '/admin/usage',
    },
    {
      id: 'settings-audit',
      title: 'settings-audit',
      icon: Activity,
      category: 'SecurityAudit',
      appId: 'settings',
      absolutePath: '/admin/audit',
    },
  ],
  workspaceRoutePaths: [],
  staticWorkspaceRoutePaths: ['/w/:workspaceSlug/settings'],
  globalRoutePaths: [],
  staticGlobalRoutePaths: [
    '/admin',
    '/admin/apps',
    '/admin/users',
    '/admin/teams',
    '/admin/general',
    '/admin/people',
    '/admin/hr',
    '/admin/apps/platform',
    '/admin/apps/workspace',
    '/admin/apps/app-bar',
    '/admin/llm',
    '/admin/model-monitoring',
    '/admin/document-processing',
    '/admin/ai-security',
    '/admin/workspaces',
    '/admin/community',
    '/admin/api-keys',
    '/admin/batches',
    '/admin/usage',
    '/admin/audit',
  ],
};
