"""Compatibility imports for the streaming chat event envelope contract."""

from __future__ import annotations

from open_work_hub_api.domains.ai.stream_envelopes import (
    ENVELOPE_SCHEMA_ADAPTER,
    PUBLISHED_EVENT_TYPES,
    AgentEventEnvelope,
    ApprovalRequiredData,
    ApprovalRequiredEvent,
    ApprovalResolvedData,
    ApprovalResolvedEvent,
    ArtifactCompletedData,
    ArtifactCompletedEvent,
    ArtifactDeltaData,
    ArtifactDeltaEvent,
    ArtifactStartedData,
    ArtifactStartedEvent,
    ContentDeltaData,
    ContentDeltaEvent,
    ConversationAttachedData,
    ConversationAttachedEvent,
    DoneData,
    DoneEvent,
    DoneFinishReason,
    DoneMeta,
    EnvelopeEncoder,
    ErrorData,
    ErrorEvent,
    ReasoningDeltaData,
    ReasoningDeltaEvent,
    ToolCallArgsDeltaData,
    ToolCallArgsDeltaEvent,
    ToolCallStartedData,
    ToolCallStartedEvent,
    ToolResultData,
    ToolResultEvent,
    UsageData,
    UsageEvent,
    envelope_schema,
    make_envelope,
    serialize_sse,
)

_ENVELOPE_ADAPTER = ENVELOPE_SCHEMA_ADAPTER
_PUBLISHED_TYPES = PUBLISHED_EVENT_TYPES

__all__ = [
    "AgentEventEnvelope",
    "ApprovalRequiredData",
    "ApprovalRequiredEvent",
    "ApprovalResolvedData",
    "ApprovalResolvedEvent",
    "ArtifactCompletedData",
    "ArtifactCompletedEvent",
    "ArtifactDeltaData",
    "ArtifactDeltaEvent",
    "ArtifactStartedData",
    "ArtifactStartedEvent",
    "ContentDeltaData",
    "ContentDeltaEvent",
    "ConversationAttachedData",
    "ConversationAttachedEvent",
    "DoneData",
    "DoneEvent",
    "DoneFinishReason",
    "DoneMeta",
    "ENVELOPE_SCHEMA_ADAPTER",
    "EnvelopeEncoder",
    "ErrorData",
    "ErrorEvent",
    "PUBLISHED_EVENT_TYPES",
    "ReasoningDeltaData",
    "ReasoningDeltaEvent",
    "ToolCallArgsDeltaData",
    "ToolCallArgsDeltaEvent",
    "ToolCallStartedData",
    "ToolCallStartedEvent",
    "ToolResultData",
    "ToolResultEvent",
    "UsageData",
    "UsageEvent",
    "envelope_schema",
    "make_envelope",
    "serialize_sse",
]
