from open_work_hub_api.core.app_registry import (
    AppNavRegistration,
    app_registration,
)

MAIL_APP = app_registration(
    "mail",
    nav_items=(
        AppNavRegistration(
            id="mail-inbox",
            title="Inbox",
            category="Mail",
            icon_key="inbox",
        ),
        AppNavRegistration(
            id="mail-unread",
            title="Unread",
            category="Mail",
            icon_key="mail-open",
            path_suffix="?unread=true",
        ),
        AppNavRegistration(
            id="mail-starred",
            title="Starred",
            category="Mail",
            icon_key="star",
            path_suffix="?starred=true",
        ),
        AppNavRegistration(
            id="mail-drafts",
            title="Drafts",
            category="Mail",
            icon_key="file-pen-line",
            path_suffix="?view=drafts",
        ),
        AppNavRegistration(
            id="mail-settings",
            title="Settings",
            category="Mail",
            icon_key="settings",
            path_suffix="?view=settings",
        ),
    ),
)
