"""baseline_2026_04_10

Revision ID: 0b843a383b2b
Revises: 
Create Date: 2026-04-10 18:25:44.991642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b843a383b2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group_kind', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_groups_active'), 'access_groups', ['active'], unique=False)
    op.create_index(op.f('ix_access_groups_group_kind'), 'access_groups', ['group_kind'], unique=False)
    op.create_index(op.f('ix_access_groups_name'), 'access_groups', ['name'], unique=False)
    op.create_index(op.f('ix_access_groups_slug'), 'access_groups', ['slug'], unique=True)
    op.create_table('feature_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required_permissions', sa.JSON(), nullable=False),
    sa.Column('allowed_workspace_keys', sa.JSON(), nullable=False),
    sa.Column('allowed_group_slugs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_policies_code'), 'feature_policies', ['code'], unique=True)
    op.create_index(op.f('ix_feature_policies_enabled'), 'feature_policies', ['enabled'], unique=False)
    op.create_table('org_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_units_active'), 'org_units', ['active'], unique=False)
    op.create_index(op.f('ix_org_units_name'), 'org_units', ['name'], unique=False)
    op.create_index(op.f('ix_org_units_parent_id'), 'org_units', ['parent_id'], unique=False)
    op.create_index(op.f('ix_org_units_slug'), 'org_units', ['slug'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_active'), 'workspaces', ['active'], unique=False)
    op.create_index(op.f('ix_workspaces_key'), 'workspaces', ['key'], unique=True)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_table('group_system_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['access_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'role', name='uq_group_system_role')
    )
    op.create_index(op.f('ix_group_system_roles_group_id'), 'group_system_roles', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_system_roles_role'), 'group_system_roles', ['role'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_workspace_team_key')
    )
    op.create_index(op.f('ix_teams_active'), 'teams', ['active'], unique=False)
    op.create_index(op.f('ix_teams_key'), 'teams', ['key'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_trashed_at'), 'teams', ['trashed_at'], unique=False)
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('employee_code', sa.String(length=40), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('theme_preference', sa.String(length=16), nullable=False),
    sa.Column('primary_org_unit_id', sa.String(length=36), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_org_unit_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=False)
    op.create_index(op.f('ix_users_primary_org_unit_id'), 'users', ['primary_org_unit_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('workspace_group_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['access_groups.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'group_id', name='uq_workspace_group')
    )
    op.create_index(op.f('ix_workspace_group_bindings_group_id'), 'workspace_group_bindings', ['group_id'], unique=False)
    op.create_index(op.f('ix_workspace_group_bindings_role'), 'workspace_group_bindings', ['role'], unique=False)
    op.create_index(op.f('ix_workspace_group_bindings_workspace_id'), 'workspace_group_bindings', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_kind', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_kind'), 'audit_logs', ['entity_kind'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('docs_native_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_native_docs_owner_id'), 'docs_native_docs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_docs_native_docs_trashed_at'), 'docs_native_docs', ['trashed_at'], unique=False)
    op.create_table('docs_user_item_prefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_doc_id', sa.String(length=36), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_viewed_page_source_id', sa.String(length=36), nullable=True),
    sa.Column('last_viewed_page_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_doc_id', name='uq_docs_user_item_pref')
    )
    op.create_index(op.f('ix_docs_user_item_prefs_source_doc_id'), 'docs_user_item_prefs', ['source_doc_id'], unique=False)
    op.create_index(op.f('ix_docs_user_item_prefs_source_type'), 'docs_user_item_prefs', ['source_type'], unique=False)
    op.create_index(op.f('ix_docs_user_item_prefs_user_id'), 'docs_user_item_prefs', ['user_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_media_files_resource', 'media_files', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_media_files_uploaded_by_id'), 'media_files', ['uploaded_by_id'], unique=False)
    op.create_table('pms_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_folders_team_id'), 'pms_folders', ['team_id'], unique=False)
    op.create_table('pms_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=24), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_notifications_is_read'), 'pms_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_pms_notifications_reference_id'), 'pms_notifications', ['reference_id'], unique=False)
    op.create_index(op.f('ix_pms_notifications_type'), 'pms_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_pms_notifications_user_id'), 'pms_notifications', ['user_id'], unique=False)
    op.create_table('pms_space_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_space_docs_created_by_id'), 'pms_space_docs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pms_space_docs_team_id'), 'pms_space_docs', ['team_id'], unique=False)
    op.create_index(op.f('ix_pms_space_docs_trashed_at'), 'pms_space_docs', ['trashed_at'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_role'), 'team_members', ['role'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('user_access_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['access_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_access_group')
    )
    op.create_index(op.f('ix_user_access_groups_group_id'), 'user_access_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_access_groups_user_id'), 'user_access_groups', ['user_id'], unique=False)
    op.create_table('user_system_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_system_role')
    )
    op.create_index(op.f('ix_user_system_roles_role'), 'user_system_roles', ['role'], unique=False)
    op.create_index(op.f('ix_user_system_roles_user_id'), 'user_system_roles', ['user_id'], unique=False)
    op.create_table('workspace_user_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_index(op.f('ix_workspace_user_bindings_role'), 'workspace_user_bindings', ['role'], unique=False)
    op.create_index(op.f('ix_workspace_user_bindings_user_id'), 'workspace_user_bindings', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_user_bindings_workspace_id'), 'workspace_user_bindings', ['workspace_id'], unique=False)
    op.create_table('docs_native_doc_link_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['docs_native_docs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', name='uq_docs_native_doc_link_share_doc')
    )
    op.create_index(op.f('ix_docs_native_doc_link_shares_active'), 'docs_native_doc_link_shares', ['active'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_link_shares_created_by_id'), 'docs_native_doc_link_shares', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_link_shares_doc_id'), 'docs_native_doc_link_shares', ['doc_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_link_shares_token'), 'docs_native_doc_link_shares', ['token'], unique=True)
    op.create_table('docs_native_doc_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_blocks', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['docs_native_docs.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['docs_native_doc_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_native_doc_pages_created_by_id'), 'docs_native_doc_pages', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_pages_doc_id'), 'docs_native_doc_pages', ['doc_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_pages_parent_id'), 'docs_native_doc_pages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_pages_trashed_at'), 'docs_native_doc_pages', ['trashed_at'], unique=False)
    op.create_table('docs_native_doc_user_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['docs_native_docs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'user_id', name='uq_docs_native_doc_user_share')
    )
    op.create_index(op.f('ix_docs_native_doc_user_shares_created_by_id'), 'docs_native_doc_user_shares', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_user_shares_doc_id'), 'docs_native_doc_user_shares', ['doc_id'], unique=False)
    op.create_index(op.f('ix_docs_native_doc_user_shares_user_id'), 'docs_native_doc_user_shares', ['user_id'], unique=False)
    op.create_table('pms_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['pms_folders.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_projects_archived'), 'pms_projects', ['archived'], unique=False)
    op.create_index(op.f('ix_pms_projects_created_by_id'), 'pms_projects', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pms_projects_folder_id'), 'pms_projects', ['folder_id'], unique=False)
    op.create_index(op.f('ix_pms_projects_key'), 'pms_projects', ['key'], unique=True)
    op.create_index(op.f('ix_pms_projects_name'), 'pms_projects', ['name'], unique=False)
    op.create_index(op.f('ix_pms_projects_status'), 'pms_projects', ['status'], unique=False)
    op.create_index(op.f('ix_pms_projects_team_id'), 'pms_projects', ['team_id'], unique=False)
    op.create_table('pms_space_doc_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('space_doc_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_blocks', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pms_space_doc_pages.id'], ),
    sa.ForeignKeyConstraint(['space_doc_id'], ['pms_space_docs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_space_doc_pages_created_by_id'), 'pms_space_doc_pages', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pms_space_doc_pages_parent_id'), 'pms_space_doc_pages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pms_space_doc_pages_space_doc_id'), 'pms_space_doc_pages', ['space_doc_id'], unique=False)
    op.create_index(op.f('ix_pms_space_doc_pages_team_id'), 'pms_space_doc_pages', ['team_id'], unique=False)
    op.create_index(op.f('ix_pms_space_doc_pages_trashed_at'), 'pms_space_doc_pages', ['trashed_at'], unique=False)
    op.create_table('pms_user_doc_prefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('space_doc_id', sa.String(length=36), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_doc_id'], ['pms_space_docs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'space_doc_id', name='uq_user_doc_pref')
    )
    op.create_index(op.f('ix_pms_user_doc_prefs_space_doc_id'), 'pms_user_doc_prefs', ['space_doc_id'], unique=False)
    op.create_index(op.f('ix_pms_user_doc_prefs_user_id'), 'pms_user_doc_prefs', ['user_id'], unique=False)
    op.create_table('pms_custom_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=24), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_custom_fields_project_id'), 'pms_custom_fields', ['project_id'], unique=False)
    op.create_table('pms_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_pms_label_name')
    )
    op.create_index(op.f('ix_pms_labels_project_id'), 'pms_labels', ['project_id'], unique=False)
    op.create_table('pms_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_milestones_project_id'), 'pms_milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_pms_milestones_status'), 'pms_milestones', ['status'], unique=False)
    op.create_table('pms_project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_pms_member')
    )
    op.create_index(op.f('ix_pms_project_members_project_id'), 'pms_project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_pms_project_members_user_id'), 'pms_project_members', ['user_id'], unique=False)
    op.create_table('pms_project_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_pms_project_status_slug')
    )
    op.create_index(op.f('ix_pms_project_statuses_project_id'), 'pms_project_statuses', ['project_id'], unique=False)
    op.create_index(op.f('ix_pms_project_statuses_slug'), 'pms_project_statuses', ['slug'], unique=False)
    op.create_table('pms_schedule_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('predecessor_kind', sa.String(length=24), nullable=False),
    sa.Column('predecessor_id', sa.String(length=36), nullable=False),
    sa.Column('successor_kind', sa.String(length=24), nullable=False),
    sa.Column('successor_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_schedule_dependencies_predecessor_id'), 'pms_schedule_dependencies', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_pms_schedule_dependencies_project_id'), 'pms_schedule_dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_pms_schedule_dependencies_successor_id'), 'pms_schedule_dependencies', ['successor_id'], unique=False)
    op.create_table('pms_task_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_status', sa.String(length=40), nullable=False),
    sa.Column('default_priority', sa.String(length=24), nullable=False),
    sa.Column('checklist_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_task_templates_project_id'), 'pms_task_templates', ['project_id'], unique=False)
    op.create_table('pms_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_blocks', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=24), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('board_position', sa.Integer(), nullable=False),
    sa.Column('estimate_hours', sa.Float(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=120), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['pms_milestones.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pms_issues.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pms_projects.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'issue_number', name='uq_pms_issue_number')
    )
    op.create_index(op.f('ix_pms_issues_archived'), 'pms_issues', ['archived'], unique=False)
    op.create_index(op.f('ix_pms_issues_assignee_id'), 'pms_issues', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_pms_issues_milestone_id'), 'pms_issues', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_pms_issues_parent_id'), 'pms_issues', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pms_issues_priority'), 'pms_issues', ['priority'], unique=False)
    op.create_index(op.f('ix_pms_issues_project_id'), 'pms_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_pms_issues_reporter_id'), 'pms_issues', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_pms_issues_status'), 'pms_issues', ['status'], unique=False)
    op.create_index(op.f('ix_pms_issues_title'), 'pms_issues', ['title'], unique=False)
    op.create_table('pms_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_pms_attachments_issue_id'), 'pms_attachments', ['issue_id'], unique=False)
    op.create_index(op.f('ix_pms_attachments_uploaded_by_id'), 'pms_attachments', ['uploaded_by_id'], unique=False)
    op.create_table('pms_checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_checklist_items_issue_id'), 'pms_checklist_items', ['issue_id'], unique=False)
    op.create_table('pms_custom_field_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['pms_custom_fields.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'field_id', name='uq_pms_cf_value')
    )
    op.create_index(op.f('ix_pms_custom_field_values_field_id'), 'pms_custom_field_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_pms_custom_field_values_issue_id'), 'pms_custom_field_values', ['issue_id'], unique=False)
    op.create_table('pms_issue_activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=40), nullable=True),
    sa.Column('from_value', sa.String(length=255), nullable=True),
    sa.Column('to_value', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_issue_activity_logs_action'), 'pms_issue_activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_pms_issue_activity_logs_actor_id'), 'pms_issue_activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_pms_issue_activity_logs_issue_id'), 'pms_issue_activity_logs', ['issue_id'], unique=False)
    op.create_table('pms_issue_assignees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'user_id', name='uq_pms_issue_assignee')
    )
    op.create_index(op.f('ix_pms_issue_assignees_issue_id'), 'pms_issue_assignees', ['issue_id'], unique=False)
    op.create_index(op.f('ix_pms_issue_assignees_user_id'), 'pms_issue_assignees', ['user_id'], unique=False)
    op.create_table('pms_issue_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_blocks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_issue_comments_author_id'), 'pms_issue_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_pms_issue_comments_issue_id'), 'pms_issue_comments', ['issue_id'], unique=False)
    op.create_table('pms_issue_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('label_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['pms_labels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'label_id', name='uq_pms_issue_label')
    )
    op.create_index(op.f('ix_pms_issue_labels_issue_id'), 'pms_issue_labels', ['issue_id'], unique=False)
    op.create_index(op.f('ix_pms_issue_labels_label_id'), 'pms_issue_labels', ['label_id'], unique=False)
    op.create_table('pms_time_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_time_entries_issue_id'), 'pms_time_entries', ['issue_id'], unique=False)
    op.create_index(op.f('ix_pms_time_entries_user_id'), 'pms_time_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pms_time_entries_user_id'), table_name='pms_time_entries')
    op.drop_index(op.f('ix_pms_time_entries_issue_id'), table_name='pms_time_entries')
    op.drop_table('pms_time_entries')
    op.drop_index(op.f('ix_pms_issue_labels_label_id'), table_name='pms_issue_labels')
    op.drop_index(op.f('ix_pms_issue_labels_issue_id'), table_name='pms_issue_labels')
    op.drop_table('pms_issue_labels')
    op.drop_index(op.f('ix_pms_issue_comments_issue_id'), table_name='pms_issue_comments')
    op.drop_index(op.f('ix_pms_issue_comments_author_id'), table_name='pms_issue_comments')
    op.drop_table('pms_issue_comments')
    op.drop_index(op.f('ix_pms_issue_assignees_user_id'), table_name='pms_issue_assignees')
    op.drop_index(op.f('ix_pms_issue_assignees_issue_id'), table_name='pms_issue_assignees')
    op.drop_table('pms_issue_assignees')
    op.drop_index(op.f('ix_pms_issue_activity_logs_issue_id'), table_name='pms_issue_activity_logs')
    op.drop_index(op.f('ix_pms_issue_activity_logs_actor_id'), table_name='pms_issue_activity_logs')
    op.drop_index(op.f('ix_pms_issue_activity_logs_action'), table_name='pms_issue_activity_logs')
    op.drop_table('pms_issue_activity_logs')
    op.drop_index(op.f('ix_pms_custom_field_values_issue_id'), table_name='pms_custom_field_values')
    op.drop_index(op.f('ix_pms_custom_field_values_field_id'), table_name='pms_custom_field_values')
    op.drop_table('pms_custom_field_values')
    op.drop_index(op.f('ix_pms_checklist_items_issue_id'), table_name='pms_checklist_items')
    op.drop_table('pms_checklist_items')
    op.drop_index(op.f('ix_pms_attachments_uploaded_by_id'), table_name='pms_attachments')
    op.drop_index(op.f('ix_pms_attachments_issue_id'), table_name='pms_attachments')
    op.drop_table('pms_attachments')
    op.drop_index(op.f('ix_pms_issues_title'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_status'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_reporter_id'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_project_id'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_priority'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_parent_id'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_milestone_id'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_assignee_id'), table_name='pms_issues')
    op.drop_index(op.f('ix_pms_issues_archived'), table_name='pms_issues')
    op.drop_table('pms_issues')
    op.drop_index(op.f('ix_pms_task_templates_project_id'), table_name='pms_task_templates')
    op.drop_table('pms_task_templates')
    op.drop_index(op.f('ix_pms_schedule_dependencies_successor_id'), table_name='pms_schedule_dependencies')
    op.drop_index(op.f('ix_pms_schedule_dependencies_project_id'), table_name='pms_schedule_dependencies')
    op.drop_index(op.f('ix_pms_schedule_dependencies_predecessor_id'), table_name='pms_schedule_dependencies')
    op.drop_table('pms_schedule_dependencies')
    op.drop_index(op.f('ix_pms_project_statuses_slug'), table_name='pms_project_statuses')
    op.drop_index(op.f('ix_pms_project_statuses_project_id'), table_name='pms_project_statuses')
    op.drop_table('pms_project_statuses')
    op.drop_index(op.f('ix_pms_project_members_user_id'), table_name='pms_project_members')
    op.drop_index(op.f('ix_pms_project_members_project_id'), table_name='pms_project_members')
    op.drop_table('pms_project_members')
    op.drop_index(op.f('ix_pms_milestones_status'), table_name='pms_milestones')
    op.drop_index(op.f('ix_pms_milestones_project_id'), table_name='pms_milestones')
    op.drop_table('pms_milestones')
    op.drop_index(op.f('ix_pms_labels_project_id'), table_name='pms_labels')
    op.drop_table('pms_labels')
    op.drop_index(op.f('ix_pms_custom_fields_project_id'), table_name='pms_custom_fields')
    op.drop_table('pms_custom_fields')
    op.drop_index(op.f('ix_pms_user_doc_prefs_user_id'), table_name='pms_user_doc_prefs')
    op.drop_index(op.f('ix_pms_user_doc_prefs_space_doc_id'), table_name='pms_user_doc_prefs')
    op.drop_table('pms_user_doc_prefs')
    op.drop_index(op.f('ix_pms_space_doc_pages_trashed_at'), table_name='pms_space_doc_pages')
    op.drop_index(op.f('ix_pms_space_doc_pages_team_id'), table_name='pms_space_doc_pages')
    op.drop_index(op.f('ix_pms_space_doc_pages_space_doc_id'), table_name='pms_space_doc_pages')
    op.drop_index(op.f('ix_pms_space_doc_pages_parent_id'), table_name='pms_space_doc_pages')
    op.drop_index(op.f('ix_pms_space_doc_pages_created_by_id'), table_name='pms_space_doc_pages')
    op.drop_table('pms_space_doc_pages')
    op.drop_index(op.f('ix_pms_projects_team_id'), table_name='pms_projects')
    op.drop_index(op.f('ix_pms_projects_status'), table_name='pms_projects')
    op.drop_index(op.f('ix_pms_projects_name'), table_name='pms_projects')
    op.drop_index(op.f('ix_pms_projects_key'), table_name='pms_projects')
    op.drop_index(op.f('ix_pms_projects_folder_id'), table_name='pms_projects')
    op.drop_index(op.f('ix_pms_projects_created_by_id'), table_name='pms_projects')
    op.drop_index(op.f('ix_pms_projects_archived'), table_name='pms_projects')
    op.drop_table('pms_projects')
    op.drop_index(op.f('ix_docs_native_doc_user_shares_user_id'), table_name='docs_native_doc_user_shares')
    op.drop_index(op.f('ix_docs_native_doc_user_shares_doc_id'), table_name='docs_native_doc_user_shares')
    op.drop_index(op.f('ix_docs_native_doc_user_shares_created_by_id'), table_name='docs_native_doc_user_shares')
    op.drop_table('docs_native_doc_user_shares')
    op.drop_index(op.f('ix_docs_native_doc_pages_trashed_at'), table_name='docs_native_doc_pages')
    op.drop_index(op.f('ix_docs_native_doc_pages_parent_id'), table_name='docs_native_doc_pages')
    op.drop_index(op.f('ix_docs_native_doc_pages_doc_id'), table_name='docs_native_doc_pages')
    op.drop_index(op.f('ix_docs_native_doc_pages_created_by_id'), table_name='docs_native_doc_pages')
    op.drop_table('docs_native_doc_pages')
    op.drop_index(op.f('ix_docs_native_doc_link_shares_token'), table_name='docs_native_doc_link_shares')
    op.drop_index(op.f('ix_docs_native_doc_link_shares_doc_id'), table_name='docs_native_doc_link_shares')
    op.drop_index(op.f('ix_docs_native_doc_link_shares_created_by_id'), table_name='docs_native_doc_link_shares')
    op.drop_index(op.f('ix_docs_native_doc_link_shares_active'), table_name='docs_native_doc_link_shares')
    op.drop_table('docs_native_doc_link_shares')
    op.drop_index(op.f('ix_workspace_user_bindings_workspace_id'), table_name='workspace_user_bindings')
    op.drop_index(op.f('ix_workspace_user_bindings_user_id'), table_name='workspace_user_bindings')
    op.drop_index(op.f('ix_workspace_user_bindings_role'), table_name='workspace_user_bindings')
    op.drop_table('workspace_user_bindings')
    op.drop_index(op.f('ix_user_system_roles_user_id'), table_name='user_system_roles')
    op.drop_index(op.f('ix_user_system_roles_role'), table_name='user_system_roles')
    op.drop_table('user_system_roles')
    op.drop_index(op.f('ix_user_access_groups_user_id'), table_name='user_access_groups')
    op.drop_index(op.f('ix_user_access_groups_group_id'), table_name='user_access_groups')
    op.drop_table('user_access_groups')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_role'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_pms_space_docs_trashed_at'), table_name='pms_space_docs')
    op.drop_index(op.f('ix_pms_space_docs_team_id'), table_name='pms_space_docs')
    op.drop_index(op.f('ix_pms_space_docs_created_by_id'), table_name='pms_space_docs')
    op.drop_table('pms_space_docs')
    op.drop_index(op.f('ix_pms_notifications_user_id'), table_name='pms_notifications')
    op.drop_index(op.f('ix_pms_notifications_type'), table_name='pms_notifications')
    op.drop_index(op.f('ix_pms_notifications_reference_id'), table_name='pms_notifications')
    op.drop_index(op.f('ix_pms_notifications_is_read'), table_name='pms_notifications')
    op.drop_table('pms_notifications')
    op.drop_index(op.f('ix_pms_folders_team_id'), table_name='pms_folders')
    op.drop_table('pms_folders')
    op.drop_index(op.f('ix_media_files_uploaded_by_id'), table_name='media_files')
    op.drop_index('ix_media_files_resource', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_docs_user_item_prefs_user_id'), table_name='docs_user_item_prefs')
    op.drop_index(op.f('ix_docs_user_item_prefs_source_type'), table_name='docs_user_item_prefs')
    op.drop_index(op.f('ix_docs_user_item_prefs_source_doc_id'), table_name='docs_user_item_prefs')
    op.drop_table('docs_user_item_prefs')
    op.drop_index(op.f('ix_docs_native_docs_trashed_at'), table_name='docs_native_docs')
    op.drop_index(op.f('ix_docs_native_docs_owner_id'), table_name='docs_native_docs')
    op.drop_table('docs_native_docs')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_logs_entity_kind'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workspace_group_bindings_workspace_id'), table_name='workspace_group_bindings')
    op.drop_index(op.f('ix_workspace_group_bindings_role'), table_name='workspace_group_bindings')
    op.drop_index(op.f('ix_workspace_group_bindings_group_id'), table_name='workspace_group_bindings')
    op.drop_table('workspace_group_bindings')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_primary_org_unit_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_trashed_at'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_key'), table_name='teams')
    op.drop_index(op.f('ix_teams_active'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_group_system_roles_role'), table_name='group_system_roles')
    op.drop_index(op.f('ix_group_system_roles_group_id'), table_name='group_system_roles')
    op.drop_table('group_system_roles')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_key'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_active'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_org_units_slug'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_parent_id'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_name'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_active'), table_name='org_units')
    op.drop_table('org_units')
    op.drop_index(op.f('ix_feature_policies_enabled'), table_name='feature_policies')
    op.drop_index(op.f('ix_feature_policies_code'), table_name='feature_policies')
    op.drop_table('feature_policies')
    op.drop_index(op.f('ix_access_groups_slug'), table_name='access_groups')
    op.drop_index(op.f('ix_access_groups_name'), table_name='access_groups')
    op.drop_index(op.f('ix_access_groups_group_kind'), table_name='access_groups')
    op.drop_index(op.f('ix_access_groups_active'), table_name='access_groups')
    op.drop_table('access_groups')
    # ### end Alembic commands ###
