"""add_meeting_file_attachments

Revision ID: 13e887cfb1db
Revises: d8fe1ed8923a
Create Date: 2026-04-10 21:13:29.757388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e887cfb1db'
down_revision: Union[str, Sequence[str], None] = 'd8fe1ed8923a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_file_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('added_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_meeting_file_attachments_added_by_id'), 'meeting_file_attachments', ['added_by_id'], unique=False)
    op.create_index(op.f('ix_meeting_file_attachments_meeting_id'), 'meeting_file_attachments', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_file_attachments_meeting_id'), table_name='meeting_file_attachments')
    op.drop_index(op.f('ix_meeting_file_attachments_added_by_id'), table_name='meeting_file_attachments')
    op.drop_table('meeting_file_attachments')
    # ### end Alembic commands ###
