"""add_meeting_tables

Revision ID: d8fe1ed8923a
Revises: 0b843a383b2b
Create Date: 2026-04-10 18:59:04.353511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fe1ed8923a'
down_revision: Union[str, Sequence[str], None] = '0b843a383b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('organizer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_organizer_id'), 'meetings', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_workspace_id'), 'meetings', ['workspace_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('response', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_attendee')
    )
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_user_id'), 'meeting_attendees', ['user_id'], unique=False)
    op.create_table('meeting_doc_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('added_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['docs_native_docs.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'doc_id', name='uq_meeting_doc_link')
    )
    op.create_index(op.f('ix_meeting_doc_links_doc_id'), 'meeting_doc_links', ['doc_id'], unique=False)
    op.create_index(op.f('ix_meeting_doc_links_meeting_id'), 'meeting_doc_links', ['meeting_id'], unique=False)
    op.create_table('meeting_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('transcription_status', sa.String(length=24), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('linked_doc_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_doc_id'], ['docs_native_docs.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_meeting_recordings_meeting_id'), 'meeting_recordings', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_recordings_transcription_status'), 'meeting_recordings', ['transcription_status'], unique=False)
    op.create_table('meeting_task_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('added_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['pms_issues.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'issue_id', name='uq_meeting_task_link')
    )
    op.create_index(op.f('ix_meeting_task_links_issue_id'), 'meeting_task_links', ['issue_id'], unique=False)
    op.create_index(op.f('ix_meeting_task_links_meeting_id'), 'meeting_task_links', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_task_links_meeting_id'), table_name='meeting_task_links')
    op.drop_index(op.f('ix_meeting_task_links_issue_id'), table_name='meeting_task_links')
    op.drop_table('meeting_task_links')
    op.drop_index(op.f('ix_meeting_recordings_transcription_status'), table_name='meeting_recordings')
    op.drop_index(op.f('ix_meeting_recordings_meeting_id'), table_name='meeting_recordings')
    op.drop_table('meeting_recordings')
    op.drop_index(op.f('ix_meeting_doc_links_meeting_id'), table_name='meeting_doc_links')
    op.drop_index(op.f('ix_meeting_doc_links_doc_id'), table_name='meeting_doc_links')
    op.drop_table('meeting_doc_links')
    op.drop_index(op.f('ix_meeting_attendees_user_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index(op.f('ix_meetings_workspace_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organizer_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
