export {
  CORE_SUB_SIDEBAR_CREATE_MENU_GAP as SUB_SIDEBAR_CREATE_MENU_GAP,
  CORE_SUB_SIDEBAR_CREATE_MENU_INSET as SUB_SIDEBAR_CREATE_MENU_INSET,
  CORE_SUB_SIDEBAR_CREATE_MENU_WIDTH as SUB_SIDEBAR_CREATE_MENU_WIDTH,
  CORE_SUB_SIDEBAR_DEFAULT_WIDTH as SUB_SIDEBAR_DEFAULT_WIDTH,
  CORE_SUB_SIDEBAR_MAIN_NAV_WIDTH as SUB_SIDEBAR_MAIN_NAV_WIDTH,
  CORE_SUB_SIDEBAR_MAX_WIDTH as SUB_SIDEBAR_MAX_WIDTH,
  CORE_SUB_SIDEBAR_MIN_WIDTH as SUB_SIDEBAR_MIN_WIDTH,
  CORE_SUB_SIDEBAR_PINNED_STORAGE_KEY as SUB_SIDEBAR_PINNED_STORAGE_KEY,
  calculateCoreSubSidebarCreateMenuPosition as calculateSubSidebarCreateMenuPosition,
  clampCoreSubSidebarWidth as clampSubSidebarWidth,
  isCoreSubSidebarCreateMenuOpen as isSubSidebarCreateMenuOpen,
  restoreCoreSubSidebarCollapsed as restoreSubSidebarCollapsed,
  restoreCoreSubSidebarPinned as restoreSubSidebarPinned,
  restoreCoreSubSidebarWidth as restoreSubSidebarWidth,
  resolveCoreSubSidebarPreviewOpenAfterPinnedChange as resolveSubSidebarPreviewOpenAfterPinnedChange,
  serializeCoreSubSidebarCollapsed as serializeSubSidebarCollapsed,
  serializeCoreSubSidebarPinned as serializeSubSidebarPinned,
  setCoreSubSidebarCreateMenuOpen as setSubSidebarCreateMenuOpen,
  type CoreSubSidebarCreateMenuPosition as SubSidebarCreateMenuPosition,
  type CoreSubSidebarCreateMenuState as SubSidebarCreateMenuState,
  type CoreSubSidebarRect as SubSidebarRect,
  widthFromCoreSubSidebarPointer as widthFromSubSidebarPointer,
} from '@open-work-hub/core-web/sub-sidebar-frame';
